/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenFoodFactsOpenApi);
  }
}(this, function(expect, OpenFoodFactsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Nutriscore2023Data', function() {
    it('should create an instance of Nutriscore2023Data', function() {
      // uncomment below and update the code to test Nutriscore2023Data
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be.a(OpenFoodFactsOpenApi.Nutriscore2023Data);
    });

    it('should have the property is_beverage (base name: "is_beverage")', function() {
      // uncomment below and update the code to test the property is_beverage
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property is_cheese (base name: "is_cheese")', function() {
      // uncomment below and update the code to test the property is_cheese
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property is_water (base name: "is_water")', function() {
      // uncomment below and update the code to test the property is_water
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property is_fat_oil_nuts_seeds (base name: "is_fat_oil_nuts_seeds")', function() {
      // uncomment below and update the code to test the property is_fat_oil_nuts_seeds
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property is_red_meat_product (base name: "is_red_meat_product")', function() {
      // uncomment below and update the code to test the property is_red_meat_product
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property components (base name: "components")', function() {
      // uncomment below and update the code to test the property components
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property count_proteins (base name: "count_proteins")', function() {
      // uncomment below and update the code to test the property count_proteins
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property count_proteins_reason (base name: "count_proteins_reason")', function() {
      // uncomment below and update the code to test the property count_proteins_reason
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property negative_points (base name: "negative_points")', function() {
      // uncomment below and update the code to test the property negative_points
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property positive_points (base name: "positive_points")', function() {
      // uncomment below and update the code to test the property positive_points
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property negative_points_max (base name: "negative_points_max")', function() {
      // uncomment below and update the code to test the property negative_points_max
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property positive_points_max (base name: "positive_points_max")', function() {
      // uncomment below and update the code to test the property positive_points_max
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

    it('should have the property positive_nutrients (base name: "positive_nutrients")', function() {
      // uncomment below and update the code to test the property positive_nutrients
      //var instance = new OpenFoodFactsOpenApi.Nutriscore2023Data();
      //expect(instance).to.be();
    });

  });

}));
