/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenFoodFactsOpenApi);
  }
}(this, function(expect, OpenFoodFactsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenFoodFactsOpenApi.Nutriscore20211();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Nutriscore20211', function() {
    it('should create an instance of Nutriscore20211', function() {
      // uncomment below and update the code to test Nutriscore20211
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be.a(OpenFoodFactsOpenApi.Nutriscore20211);
    });

    it('should have the property category_available (base name: "category_available")', function() {
      // uncomment below and update the code to test the property category_available
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be();
    });

    it('should have the property grade (base name: "grade")', function() {
      // uncomment below and update the code to test the property grade
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be();
    });

    it('should have the property nutrients_available (base name: "nutrients_available")', function() {
      // uncomment below and update the code to test the property nutrients_available
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be();
    });

    it('should have the property nutriscore_applicable (base name: "nutriscore_applicable")', function() {
      // uncomment below and update the code to test the property nutriscore_applicable
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be();
    });

    it('should have the property nutriscore_computed (base name: "nutriscore_computed")', function() {
      // uncomment below and update the code to test the property nutriscore_computed
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new OpenFoodFactsOpenApi.Nutriscore20211();
      //expect(instance).to.be();
    });

  });

}));
