#  --global-property debugModels,debugOperations,debugOpenAPI
generatorName : typescript-fetch
outputDir: /mnt/c/Projects/Iside/fe-client/api-client-ts
inputSpec: /home/shinjigi/projects/_GH/openfoodfacts/openfoodfacts-server/docs/api/ref/api.yml
verbose: false
additionalProperties:
  npmName: '@iside/fe-client-ts'
  npmVersion: '1.0.0'
  npmRepository : 'http://svn.belux.conseur.org/svn/repository/projects/internet/Euroconsumers.Core.Javascript/trunk/Vue/food-app'
  snapshot : false
  supportsES6: true
modelNameMappings:
  get_product_by_barcode_200_response: GetProductByBarcodeResponse
  get_product_by_barcode_200_response_oneOf: GetProductBaseByBarcodeResponse
  get_product_by_barcode_200_response_oneOf_allOf_product: ProductBase
  get_product_by_barcode_200_response_oneOf_1: GetProductKnowledgePanelsByBarcodeResponse
  get_product_by_barcode_200_response_oneOf_1_allOf_product: ProductKnowledgePanels