generatorName : javascript
outputDir: /mnt/c/Projects/Iside/fe-client/api-client-js
inputSpec: /home/shinjigi/projects/_GH/openfoodfacts/openfoodfacts-server/docs/api/ref/api-short.yml
verbose: false
additionaladditionalProperties:
  npmName: '@iside/fe-client-js'
  npmVersion: '1.0.0'
  npmRepository : 'http://svn.belux.conseur.org/svn/repository/projects/internet/Euroconsumers.Core.Javascript/trunk/Vue/food-app'
  snapshot : false
  supportsES6: true
modelNameMappings:
  # setStyle_setStyleQuery_parameter: SetStyleQueryParameter
  # setShouldExplode_setShouldExplodeQuery_parameter: SetShouldExplodeQueryParameter
  # Nutrient: NutrientNoSub
  # Nutrients_inner: Nutrients
  # Nutrients_inner_nutrients_inner: Nutrient