/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenFoodFactsOpenApi);
  }
}(this, function (expect, OpenFoodFactsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductAttributeGroup', function () {
    it('should create an instance of ProductAttributeGroup', function () {
      // uncomment below and update the code to test ProductAttributeGroup
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      expect(instance).to.be.a(OpenFoodFactsOpenApi.ProductAttributeGroup);
    });

    it('should have the property id (base name: "id")', function () {
      // uncomment below and update the code to test the property id
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function () {
      // uncomment below and update the code to test the property status
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function () {
      // uncomment below and update the code to test the property title
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property match (base name: "match")', function () {
      // uncomment below and update the code to test the property match
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property grade (base name: "grade")', function () {
      // uncomment below and update the code to test the property grade
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function () {
      // uncomment below and update the code to test the property name
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property iconUrl (base name: "icon_url")', function () {
      // uncomment below and update the code to test the property iconUrl
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function () {
      // uncomment below and update the code to test the property description
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

    it('should have the property descriptionShort (base name: "description_short")', function () {
      // uncomment below and update the code to test the property descriptionShort
      var instance = new OpenFoodFactsOpenApi.ProductAttributeGroup();
      //expect(instance).to.be();
    });

  });

}));
