/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ImageSizes } from '../models/ImageSizes';
import { HttpFile } from '../http/http';

/**
* This object represent an image that was uploaded to a product. \"imgid\" is an integer which is a sequential number unique to each picture. 
*/
export class Image {
    'sizes'?: ImageSizes;
    /**
    * The time the image was uploaded (as unix timestamp). 
    */
    'uploaded_t'?: string;
    /**
    * The contributor that uploaded the image. 
    */
    'uploader'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sizes",
            "baseName": "sizes",
            "type": "ImageSizes",
            "format": ""
        },
        {
            "name": "uploaded_t",
            "baseName": "uploaded_t",
            "type": "string",
            "format": ""
        },
        {
            "name": "uploader",
            "baseName": "uploader",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Image.attributeTypeMap;
    }

    public constructor() {
    }
}
