/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* All known nutrients for the product.  Note that each nutrients are declined with a variety of suffixes like `_100g`, `_serving`, see patternProperties below.  A specific `_unit` is the unit used to measure the nutrient.  Beware that some properties are to be interpreted based upon `nutrition_data_per` value.  Also for products that have a nutrition table for prepared product (eg. the nutrition facts for a bowl of milk with cocoa powder), a `_prepared` suffix is added (before other suffixes).  You can get all possible nutrients from the [nutrients taxonomy](https://static.openfoodfacts.org/data/taxonomies/nutrients.json)  **FIXME** add more nutrients with description. 
*/
export class ProductNutritionNutriments {
    /**
    * Quantity of alcohol  (per 100g or per serving) in a standard unit (g or ml) 
    */
    'alcohol'?: number;
    'carbohydrates'?: number;
    'carbohydrates_100g'?: number;
    'carbohydrates_serving'?: number;
    'carbohydrates_unit'?: ProductNutritionNutrimentsCarbohydratesUnitEnum;
    'carbohydrates_value'?: number;
    'cocoa'?: number;
    'cocoa_100g'?: number;
    'cocoa_label'?: string;
    'cocoa_serving'?: number;
    'cocoa_unit'?: ProductNutritionNutrimentsCocoaUnitEnum;
    'cocoa_value'?: number;
    /**
    * It is the same as `energy-kj` if we have it, or computed from `energy-kcal` otherwise  (per 100g or per serving) in kj 
    */
    'energy'?: number;
    'energy_100g'?: number;
    /**
    * energy_value will be equal to energy-kj_value if we have it or to energy-kcal_value otherwise 
    */
    'energy_value'?: number;
    'energy_serving'?: number;
    /**
    * Equal to energy-kj_unit if we have it or to energy-kcal_unit otherwise 
    */
    'energy_unit'?: ProductNutritionNutrimentsEnergyUnitEnum;
    /**
    * energy in kj, if it is specified  (per 100g or per serving) in a standard unit (g or ml) 
    */
    'energy_kj'?: number;
    'energy_kj_100g'?: number;
    'energy_kj_serving'?: number;
    'energy_kj_unit'?: ProductNutritionNutrimentsEnergyKjUnitEnum;
    'energy_kj_value'?: number;
    'energy_kj_value_computed'?: number;
    'fat'?: number;
    'fat_value'?: number;
    'fat_100g'?: number;
    'fat_serving'?: number;
    'fat_unit'?: string;
    'nova_group_100g'?: number;
    'nova_group_serving'?: number;
    'nutrition_score_fr_100g'?: number;
    'proteins_100g'?: number;
    'proteins_serving'?: number;
    'proteins_unit'?: string;
    'proteins_value'?: number;
    'salt_100g'?: number;
    'salt_serving'?: number;
    'salt_unit'?: string;
    'salt_value'?: number;
    'saturated_fat'?: number;
    'saturated_fat_100g'?: number;
    'saturated_fat_serving'?: number;
    'saturated_fat_unit'?: string;
    'saturated_fat_value'?: number;
    'sodium_100g'?: number;
    'sodium_serving'?: number;
    'sodium_unit'?: string;
    'sodium_value'?: number;
    'sugars_100g'?: number;
    'sugars_serving'?: number;
    'sugars_unit'?: string;
    'sugars_value'?: number;
    'fiber_100g'?: number;
    'fiber_serving'?: number;
    'fiber_unit'?: string;
    'fiber_value'?: number;
    'energy_kcal_100g'?: number;
    'energy_kcal_serving'?: number;
    'energy_kcal_unit'?: string;
    'energy_kcal_value'?: number;
    'energy_kcal_value_computed'?: number;
    /**
    * energy in kcal, if it is specified  (per 100g or per serving) in a standard unit (g or ml) 
    */
    'energy_kcal'?: number;
    'fruits_vegetables_legumes_estimate_from_ingredients_serving'?: number;
    'fruits_vegetables_legumes_estimate_from_ingredients_100g'?: number;
    /**
    * An estimate, from the ingredients list of the percentage of fruits, vegetable and legumes. This is an important information for Nutri-Score (2023 version) computation. 
    */
    'fruits_vegetables_legumes_estimate_from_ingredients'?: number;
    'fruits_vegetables_nuts_estimate_from_ingredients_serving'?: number;
    'fruits_vegetables_nuts_estimate_from_ingredients_100g'?: number;
    /**
    * An estimate, from the ingredients list of the percentage of fruits, vegetable and nuts. This is an important information for Nutri-Score (2021 version) computation. 
    */
    'fruits_vegetables_nuts_estimate_from_ingredients'?: number;
    'nova_group'?: number;
    'nutrition_score_fr'?: any | null;
    'proteins'?: number;
    'salt'?: number;
    'sodium'?: number;
    'sugars'?: number;
    'fiber'?: number;
    'carbon_footprint_from_known_ingredients_product'?: number;
    'carbon_footprint_from_known_ingredients_serving'?: number;
    /**
    * erythritol is a polyol which is not providing any energy. As such, it needs not be taken into account when computing the energy of a product. Eryhtritol is now displayed on nutrition facts sheet of some products, mainly in the USA. This value is entered either by contributors, either by imports. 
    */
    'erythritol'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "alcohol",
            "baseName": "alcohol",
            "type": "number",
            "format": ""
        },
        {
            "name": "carbohydrates",
            "baseName": "carbohydrates",
            "type": "number",
            "format": ""
        },
        {
            "name": "carbohydrates_100g",
            "baseName": "carbohydrates_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "carbohydrates_serving",
            "baseName": "carbohydrates_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "carbohydrates_unit",
            "baseName": "carbohydrates_unit",
            "type": "ProductNutritionNutrimentsCarbohydratesUnitEnum",
            "format": ""
        },
        {
            "name": "carbohydrates_value",
            "baseName": "carbohydrates_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "cocoa",
            "baseName": "cocoa",
            "type": "number",
            "format": ""
        },
        {
            "name": "cocoa_100g",
            "baseName": "cocoa_100g",
            "type": "number",
            "format": ""
        },
        {
            "name": "cocoa_label",
            "baseName": "cocoa_label",
            "type": "string",
            "format": ""
        },
        {
            "name": "cocoa_serving",
            "baseName": "cocoa_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "cocoa_unit",
            "baseName": "cocoa_unit",
            "type": "ProductNutritionNutrimentsCocoaUnitEnum",
            "format": ""
        },
        {
            "name": "cocoa_value",
            "baseName": "cocoa_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "energy",
            "baseName": "energy",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy_100g",
            "baseName": "energy_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "energy_value",
            "baseName": "energy_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy_serving",
            "baseName": "energy_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "energy_unit",
            "baseName": "energy_unit",
            "type": "ProductNutritionNutrimentsEnergyUnitEnum",
            "format": ""
        },
        {
            "name": "energy_kj",
            "baseName": "energy_kj",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy_kj_100g",
            "baseName": "energy_kj_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "energy_kj_serving",
            "baseName": "energy_kj_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "energy_kj_unit",
            "baseName": "energy_kj_unit",
            "type": "ProductNutritionNutrimentsEnergyKjUnitEnum",
            "format": ""
        },
        {
            "name": "energy_kj_value",
            "baseName": "energy_kj_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "energy_kj_value_computed",
            "baseName": "energy_kj_value_computed",
            "type": "number",
            "format": "float"
        },
        {
            "name": "fat",
            "baseName": "fat",
            "type": "number",
            "format": ""
        },
        {
            "name": "fat_value",
            "baseName": "fat_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "fat_100g",
            "baseName": "fat_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "fat_serving",
            "baseName": "fat_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "fat_unit",
            "baseName": "fat_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "nova_group_100g",
            "baseName": "nova-group_100g",
            "type": "number",
            "format": ""
        },
        {
            "name": "nova_group_serving",
            "baseName": "nova-group_serving",
            "type": "number",
            "format": ""
        },
        {
            "name": "nutrition_score_fr_100g",
            "baseName": "nutrition-score-fr_100g",
            "type": "number",
            "format": ""
        },
        {
            "name": "proteins_100g",
            "baseName": "proteins_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "proteins_serving",
            "baseName": "proteins_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "proteins_unit",
            "baseName": "proteins_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "proteins_value",
            "baseName": "proteins_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "salt_100g",
            "baseName": "salt_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "salt_serving",
            "baseName": "salt_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "salt_unit",
            "baseName": "salt_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "salt_value",
            "baseName": "salt_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "saturated_fat",
            "baseName": "saturated-fat",
            "type": "number",
            "format": ""
        },
        {
            "name": "saturated_fat_100g",
            "baseName": "saturated-fat_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "saturated_fat_serving",
            "baseName": "saturated-fat_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "saturated_fat_unit",
            "baseName": "saturated-fat_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "saturated_fat_value",
            "baseName": "saturated-fat_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "sodium_100g",
            "baseName": "sodium_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "sodium_serving",
            "baseName": "sodium_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "sodium_unit",
            "baseName": "sodium_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "sodium_value",
            "baseName": "sodium_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "sugars_100g",
            "baseName": "sugars_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "sugars_serving",
            "baseName": "sugars_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "sugars_unit",
            "baseName": "sugars_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "sugars_value",
            "baseName": "sugars_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "fiber_100g",
            "baseName": "fiber_100g",
            "type": "number",
            "format": "float"
        },
        {
            "name": "fiber_serving",
            "baseName": "fiber_serving",
            "type": "number",
            "format": "float"
        },
        {
            "name": "fiber_unit",
            "baseName": "fiber_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "fiber_value",
            "baseName": "fiber_value",
            "type": "number",
            "format": "float"
        },
        {
            "name": "energy_kcal_100g",
            "baseName": "energy-kcal_100g",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy_kcal_serving",
            "baseName": "energy-kcal_serving",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy_kcal_unit",
            "baseName": "energy-kcal_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "energy_kcal_value",
            "baseName": "energy-kcal_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy_kcal_value_computed",
            "baseName": "energy-kcal_value_computed",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy_kcal",
            "baseName": "energy-kcal",
            "type": "number",
            "format": ""
        },
        {
            "name": "fruits_vegetables_legumes_estimate_from_ingredients_serving",
            "baseName": "fruits-vegetables-legumes-estimate-from-ingredients_serving",
            "type": "number",
            "format": ""
        },
        {
            "name": "fruits_vegetables_legumes_estimate_from_ingredients_100g",
            "baseName": "fruits-vegetables-legumes-estimate-from-ingredients_100g",
            "type": "number",
            "format": ""
        },
        {
            "name": "fruits_vegetables_legumes_estimate_from_ingredients",
            "baseName": "fruits-vegetables-legumes-estimate-from-ingredients",
            "type": "number",
            "format": ""
        },
        {
            "name": "fruits_vegetables_nuts_estimate_from_ingredients_serving",
            "baseName": "fruits-vegetables-nuts-estimate-from-ingredients_serving",
            "type": "number",
            "format": ""
        },
        {
            "name": "fruits_vegetables_nuts_estimate_from_ingredients_100g",
            "baseName": "fruits-vegetables-nuts-estimate-from-ingredients_100g",
            "type": "number",
            "format": ""
        },
        {
            "name": "fruits_vegetables_nuts_estimate_from_ingredients",
            "baseName": "fruits-vegetables-nuts-estimate-from-ingredients",
            "type": "number",
            "format": ""
        },
        {
            "name": "nova_group",
            "baseName": "nova-group",
            "type": "number",
            "format": ""
        },
        {
            "name": "nutrition_score_fr",
            "baseName": "nutrition-score-fr",
            "type": "any",
            "format": ""
        },
        {
            "name": "proteins",
            "baseName": "proteins",
            "type": "number",
            "format": ""
        },
        {
            "name": "salt",
            "baseName": "salt",
            "type": "number",
            "format": ""
        },
        {
            "name": "sodium",
            "baseName": "sodium",
            "type": "number",
            "format": ""
        },
        {
            "name": "sugars",
            "baseName": "sugars",
            "type": "number",
            "format": ""
        },
        {
            "name": "fiber",
            "baseName": "fiber",
            "type": "number",
            "format": ""
        },
        {
            "name": "carbon_footprint_from_known_ingredients_product",
            "baseName": "carbon-footprint-from-known-ingredients_product",
            "type": "number",
            "format": ""
        },
        {
            "name": "carbon_footprint_from_known_ingredients_serving",
            "baseName": "carbon-footprint-from-known-ingredients_serving",
            "type": "number",
            "format": ""
        },
        {
            "name": "erythritol",
            "baseName": "erythritol",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductNutritionNutriments.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductNutritionNutrimentsCarbohydratesUnitEnum {
    g = 'g',
    mg = 'mg',
    g2 = 'μg'
}
export enum ProductNutritionNutrimentsCocoaUnitEnum {
    g = 'g',
    mg = 'mg',
    g2 = 'μg'
}
export enum ProductNutritionNutrimentsEnergyUnitEnum {
    kcal = 'kcal',
    kJ = 'kJ'
}
export enum ProductNutritionNutrimentsEnergyKjUnitEnum {
    kJ = 'kJ'
}

