/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductIngredientsIngredientsAnalysis {
    'ennon_vegan'?: Array<string>;
    'enpalm_oil_content_unknown'?: Array<string>;
    'enpalm_oil'?: Array<string>;
    'envegan_status_unknown'?: Array<string>;
    'envegetarian_status_unknown'?: Array<string>;
    'enmaybe_vegan'?: Array<string>;
    'enmaybe_vegetarian'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ennon_vegan",
            "baseName": "en:non-vegan",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "enpalm_oil_content_unknown",
            "baseName": "en:palm-oil-content-unknown",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "enpalm_oil",
            "baseName": "en:palm-oil",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "envegan_status_unknown",
            "baseName": "en:vegan-status-unknown",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "envegetarian_status_unknown",
            "baseName": "en:vegetarian-status-unknown",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "enmaybe_vegan",
            "baseName": "en:maybe-vegan",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "enmaybe_vegetarian",
            "baseName": "en:maybe-vegetarian",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductIngredientsIngredientsAnalysis.attributeTypeMap;
    }

    public constructor() {
    }
}
