/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductSelectedImages1Front } from '../models/ProductSelectedImages1Front';
import { HttpFile } from '../http/http';

/**
* URL for selected (important) images of the product.  This is very handy if you display the product to users. 
*/
export class ProductSelectedImages1 {
    'front'?: ProductSelectedImages1Front;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "front",
            "baseName": "front",
            "type": "ProductSelectedImages1Front",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductSelectedImages1.attributeTypeMap;
    }

    public constructor() {
    }
}
