/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* URLs of thumbnails image of image of type `image_type`
*/
export class ProductSelectedImagesIngredients {
    /**
    * Thumbnail urls of product image (front) adapted to display on product page 
    */
    'display'?: any;
    /**
    * Thumbnail urls of product image (front) adapted to display on product list page 
    */
    'small'?: any;
    /**
    * Thumbnail urls of product image (front) in smallest format 
    */
    'thumb'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "display",
            "baseName": "display",
            "type": "any",
            "format": ""
        },
        {
            "name": "small",
            "baseName": "small",
            "type": "any",
            "format": ""
        },
        {
            "name": "thumb",
            "baseName": "thumb",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductSelectedImagesIngredients.attributeTypeMap;
    }

    public constructor() {
    }
}
