/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* This is data that is linked to products data quality 
*/
export class ProductQuality {
    'data_quality_bugs_tags'?: Array<any>;
    'data_quality_errors_tags'?: Array<any>;
    'data_quality_info_tags'?: Array<string>;
    'data_quality_tags'?: Array<string>;
    'data_quality_warnings_tags'?: Array<string>;
    /**
    * Source of data imported from producers. 
    */
    'data_sources'?: string;
    'data_sources_tags'?: Array<string>;
    'debug_param_sorted_langs'?: Array<string>;
    'last_check_dates_tags'?: Array<string>;
    'last_checked_t'?: number;
    'last_checker'?: string;
    /**
    * comma separated list of values indicating some states of the product, like things to be done, or to be completed. See [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json) 
    */
    'states'?: string;
    'states_hierarchy'?: Array<string>;
    'states_tags'?: Array<string>;
    /**
    * Information about different aspect of the product 
    */
    'misc_tags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data_quality_bugs_tags",
            "baseName": "data_quality_bugs_tags",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "data_quality_errors_tags",
            "baseName": "data_quality_errors_tags",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "data_quality_info_tags",
            "baseName": "data_quality_info_tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "data_quality_tags",
            "baseName": "data_quality_tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "data_quality_warnings_tags",
            "baseName": "data_quality_warnings_tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "data_sources",
            "baseName": "data_sources",
            "type": "string",
            "format": ""
        },
        {
            "name": "data_sources_tags",
            "baseName": "data_sources_tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "debug_param_sorted_langs",
            "baseName": "debug_param_sorted_langs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "last_check_dates_tags",
            "baseName": "last_check_dates_tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "last_checked_t",
            "baseName": "last_checked_t",
            "type": "number",
            "format": ""
        },
        {
            "name": "last_checker",
            "baseName": "last_checker",
            "type": "string",
            "format": ""
        },
        {
            "name": "states",
            "baseName": "states",
            "type": "string",
            "format": ""
        },
        {
            "name": "states_hierarchy",
            "baseName": "states_hierarchy",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "states_tags",
            "baseName": "states_tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "misc_tags",
            "baseName": "misc_tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductQuality.attributeTypeMap;
    }

    public constructor() {
    }
}
