/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Detail of ingredients or processing that makes the products having Nova 3 or 4 
*/
export class ProductExtendedNovaGroupsMarkers {
    /**
    * Markers of level 3 
    */
    '_3'?: Array<Array<string>>;
    /**
    * Markers of level 4 
    */
    '_4'?: Array<Array<string>>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_3",
            "baseName": "3",
            "type": "Array<Array<string>>",
            "format": ""
        },
        {
            "name": "_4",
            "baseName": "4",
            "type": "Array<Array<string>>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductExtendedNovaGroupsMarkers.attributeTypeMap;
    }

    public constructor() {
    }
}
