/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductEcoscoreDataAdjustments } from '../models/ProductEcoscoreDataAdjustments';
import { ProductEcoscoreDataAgribalyse } from '../models/ProductEcoscoreDataAgribalyse';
import { ProductEcoscoreDataMissing } from '../models/ProductEcoscoreDataMissing';
import { ProductEcoscoreDataPreviousData } from '../models/ProductEcoscoreDataPreviousData';
import { HttpFile } from '../http/http';

/**
* An object about a lot of details about data needed for Eco-Score computation and complementary data of interest. 
*/
export class ProductEcoscoreData1 {
    'adjustments'?: ProductEcoscoreDataAdjustments;
    'agribalyse'?: ProductEcoscoreDataAgribalyse;
    'grade'?: string;
    'grades'?: any;
    'missing'?: ProductEcoscoreDataMissing;
    'missingDataWarning'?: number;
    'previousData'?: ProductEcoscoreDataPreviousData;
    'score'?: number;
    'scores'?: any;
    'status'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "adjustments",
            "baseName": "adjustments",
            "type": "ProductEcoscoreDataAdjustments",
            "format": ""
        },
        {
            "name": "agribalyse",
            "baseName": "agribalyse",
            "type": "ProductEcoscoreDataAgribalyse",
            "format": ""
        },
        {
            "name": "grade",
            "baseName": "grade",
            "type": "string",
            "format": ""
        },
        {
            "name": "grades",
            "baseName": "grades",
            "type": "any",
            "format": ""
        },
        {
            "name": "missing",
            "baseName": "missing",
            "type": "ProductEcoscoreDataMissing",
            "format": ""
        },
        {
            "name": "missingDataWarning",
            "baseName": "missing_data_warning",
            "type": "number",
            "format": ""
        },
        {
            "name": "previousData",
            "baseName": "previous_data",
            "type": "ProductEcoscoreDataPreviousData",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        },
        {
            "name": "scores",
            "baseName": "scores",
            "type": "any",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductEcoscoreData1.attributeTypeMap;
    }

    public constructor() {
    }
}
