/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * OpenAPI spec version: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Panels } from '../models/Panels';
import { HttpFile } from '../http/http';

/**
* Knowledge panels for a product 
*/
export class ProductKnowledgePanels {
    'knowledge_panels'?: Panels;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "knowledge_panels",
            "baseName": "knowledge_panels",
            "type": "Panels",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductKnowledgePanels.attributeTypeMap;
    }

    public constructor() {
    }
}
