/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdjustmentsOriginOfIngredient from './AdjustmentsOriginOfIngredient';

/**
 * The EcoscoreDataAdjustmentsOriginsOfIngredients model module.
 * @module model/EcoscoreDataAdjustmentsOriginsOfIngredients
 * @version 2
 */
class EcoscoreDataAdjustmentsOriginsOfIngredients {
    /**
     * Constructs a new <code>EcoscoreDataAdjustmentsOriginsOfIngredients</code>.
     * @alias module:model/EcoscoreDataAdjustmentsOriginsOfIngredients
     */
    constructor() { 
        
        EcoscoreDataAdjustmentsOriginsOfIngredients.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EcoscoreDataAdjustmentsOriginsOfIngredients</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EcoscoreDataAdjustmentsOriginsOfIngredients} obj Optional instance to populate.
     * @return {module:model/EcoscoreDataAdjustmentsOriginsOfIngredients} The populated <code>EcoscoreDataAdjustmentsOriginsOfIngredients</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EcoscoreDataAdjustmentsOriginsOfIngredients();

            if (data.hasOwnProperty('aggregated_origins')) {
                obj['aggregated_origins'] = ApiClient.convertToType(data['aggregated_origins'], [AdjustmentsOriginOfIngredient]);
            }
            if (data.hasOwnProperty('epi_score')) {
                obj['epi_score'] = ApiClient.convertToType(data['epi_score'], 'Number');
            }
            if (data.hasOwnProperty('epi_value')) {
                obj['epi_value'] = ApiClient.convertToType(data['epi_value'], 'Number');
            }
            if (data.hasOwnProperty('origins_from_origins_field')) {
                obj['origins_from_origins_field'] = ApiClient.convertToType(data['origins_from_origins_field'], ['String']);
            }
            if (data.hasOwnProperty('transportation_scores')) {
                obj['transportation_scores'] = ApiClient.convertToType(data['transportation_scores'], Object);
            }
            if (data.hasOwnProperty('transportation_values')) {
                obj['transportation_values'] = ApiClient.convertToType(data['transportation_values'], Object);
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], Object);
            }
            if (data.hasOwnProperty('warning')) {
                obj['warning'] = ApiClient.convertToType(data['warning'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EcoscoreDataAdjustmentsOriginsOfIngredients</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EcoscoreDataAdjustmentsOriginsOfIngredients</code>.
     */
    static validateJSON(data) {
        if (data['aggregated_origins']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['aggregated_origins'])) {
                throw new Error("Expected the field `aggregated_origins` to be an array in the JSON data but got " + data['aggregated_origins']);
            }
            // validate the optional field `aggregated_origins` (array)
            for (const item of data['aggregated_origins']) {
                AdjustmentsOriginOfIngredient.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['origins_from_origins_field'])) {
            throw new Error("Expected the field `origins_from_origins_field` to be an array in the JSON data but got " + data['origins_from_origins_field']);
        }
        // ensure the json data is a string
        if (data['warning'] && !(typeof data['warning'] === 'string' || data['warning'] instanceof String)) {
            throw new Error("Expected the field `warning` to be a primitive type in the JSON string but got " + data['warning']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/AdjustmentsOriginOfIngredient>} aggregated_origins
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['aggregated_origins'] = undefined;

/**
 * @member {Number} epi_score
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['epi_score'] = undefined;

/**
 * @member {Number} epi_value
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['epi_value'] = undefined;

/**
 * @member {Array.<String>} origins_from_origins_field
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['origins_from_origins_field'] = undefined;

/**
 * @member {Object} transportation_scores
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['transportation_scores'] = undefined;

/**
 * @member {Object} transportation_values
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['transportation_values'] = undefined;

/**
 * @member {Object} values
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['values'] = undefined;

/**
 * @member {String} warning
 */
EcoscoreDataAdjustmentsOriginsOfIngredients.prototype['warning'] = undefined;






export default EcoscoreDataAdjustmentsOriginsOfIngredients;

