/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PackagingComponentShape model module.
 * @module model/PackagingComponentShape
 * @version 2
 */
class PackagingComponentShape {
    /**
     * Constructs a new <code>PackagingComponentShape</code>.
     * The shape property is canonicalized using the packaging_shapes taxonomy.
     * @alias module:model/PackagingComponentShape
     */
    constructor() { 
        
        PackagingComponentShape.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PackagingComponentShape</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PackagingComponentShape} obj Optional instance to populate.
     * @return {module:model/PackagingComponentShape} The populated <code>PackagingComponentShape</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PackagingComponentShape();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('lc_name')) {
                obj['lc_name'] = ApiClient.convertToType(data['lc_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PackagingComponentShape</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PackagingComponentShape</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['lc_name'] && !(typeof data['lc_name'] === 'string' || data['lc_name'] instanceof String)) {
            throw new Error("Expected the field `lc_name` to be a primitive type in the JSON string but got " + data['lc_name']);
        }

        return true;
    }


}



/**
 * Canonical id of the entry in the taxonomy. If the value cannot be mapped to a taxonomy entry, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon.
 * @member {String} id
 */
PackagingComponentShape.prototype['id'] = undefined;

/**
 * Name of the entry in the language requested in the tags_lc field of the request. This field is returned only of tags_lc is specified. If the translation is not available, or if the entry does not exist in the taxonomy, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon.
 * @member {String} lc_name
 */
PackagingComponentShape.prototype['lc_name'] = undefined;






export default PackagingComponentShape;

