/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductSelectedImagesFront model module.
 * @module model/ProductSelectedImagesFront
 * @version 2
 */
class ProductSelectedImagesFront {
    /**
     * Constructs a new <code>ProductSelectedImagesFront</code>.
     * URLs of thumbnails image of image of type &#x60;image_type&#x60;
     * @alias module:model/ProductSelectedImagesFront
     */
    constructor() { 
        
        ProductSelectedImagesFront.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductSelectedImagesFront</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductSelectedImagesFront} obj Optional instance to populate.
     * @return {module:model/ProductSelectedImagesFront} The populated <code>ProductSelectedImagesFront</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductSelectedImagesFront();

            if (data.hasOwnProperty('display')) {
                obj['display'] = ApiClient.convertToType(data['display'], Object);
            }
            if (data.hasOwnProperty('small')) {
                obj['small'] = ApiClient.convertToType(data['small'], Object);
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductSelectedImagesFront</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductSelectedImagesFront</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Thumbnail urls of product image (front) adapted to display on product page 
 * @member {Object} display
 */
ProductSelectedImagesFront.prototype['display'] = undefined;

/**
 * Thumbnail urls of product image (front) adapted to display on product list page 
 * @member {Object} small
 */
ProductSelectedImagesFront.prototype['small'] = undefined;

/**
 * Thumbnail urls of product image (front) in smallest format 
 * @member {Object} thumb
 */
ProductSelectedImagesFront.prototype['thumb'] = undefined;






export default ProductSelectedImagesFront;

