/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TitleElement model module.
 * @module model/TitleElement
 * @version 2
 */
class TitleElement {
    /**
     * Constructs a new <code>TitleElement</code>.
     * The title of a panel.
     * @alias module:model/TitleElement
     */
    constructor() { 
        
        TitleElement.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitleElement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitleElement} obj Optional instance to populate.
     * @return {module:model/TitleElement} The populated <code>TitleElement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitleElement();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('grade')) {
                obj['grade'] = ApiClient.convertToType(data['grade'], 'String');
            }
            if (data.hasOwnProperty('icon_url')) {
                obj['icon_url'] = ApiClient.convertToType(data['icon_url'], 'String');
            }
            if (data.hasOwnProperty('icon_color_from_evaluation')) {
                obj['icon_color_from_evaluation'] = ApiClient.convertToType(data['icon_color_from_evaluation'], 'String');
            }
            if (data.hasOwnProperty('icon_size')) {
                obj['icon_size'] = ApiClient.convertToType(data['icon_size'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TitleElement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TitleElement</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['grade'] && !(typeof data['grade'] === 'string' || data['grade'] instanceof String)) {
            throw new Error("Expected the field `grade` to be a primitive type in the JSON string but got " + data['grade']);
        }
        // ensure the json data is a string
        if (data['icon_url'] && !(typeof data['icon_url'] === 'string' || data['icon_url'] instanceof String)) {
            throw new Error("Expected the field `icon_url` to be a primitive type in the JSON string but got " + data['icon_url']);
        }
        // ensure the json data is a string
        if (data['icon_color_from_evaluation'] && !(typeof data['icon_color_from_evaluation'] === 'string' || data['icon_color_from_evaluation'] instanceof String)) {
            throw new Error("Expected the field `icon_color_from_evaluation` to be a primitive type in the JSON string but got " + data['icon_color_from_evaluation']);
        }
        // ensure the json data is a string
        if (data['icon_size'] && !(typeof data['icon_size'] === 'string' || data['icon_size'] instanceof String)) {
            throw new Error("Expected the field `icon_size` to be a primitive type in the JSON string but got " + data['icon_size']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
TitleElement.prototype['title'] = undefined;

/**
 * Indicates that the panel corresponds to a A to E grade such as the Nutri-Score of the Eco-Score.
 * @member {module:model/TitleElement.GradeEnum} grade
 */
TitleElement.prototype['grade'] = undefined;

/**
 * @member {String} icon_url
 */
TitleElement.prototype['icon_url'] = undefined;

/**
 * @member {String} icon_color_from_evaluation
 */
TitleElement.prototype['icon_color_from_evaluation'] = undefined;

/**
 * If set to \"small\", the icon should be displayed at a small size. 
 * @member {String} icon_size
 */
TitleElement.prototype['icon_size'] = undefined;

/**
 * Used to indicate a special type for the title, such as \"grade\" for Nutri-Score and Eco-Score.
 * @member {String} type
 */
TitleElement.prototype['type'] = undefined;





/**
 * Allowed values for the <code>grade</code> property.
 * @enum {String}
 * @readonly
 */
TitleElement['GradeEnum'] = {

    /**
     * value: "a"
     * @const
     */
    "a": "a",

    /**
     * value: "b"
     * @const
     */
    "b": "b",

    /**
     * value: "c"
     * @const
     */
    "c": "c",

    /**
     * value: "d"
     * @const
     */
    "d": "d",

    /**
     * value: "e"
     * @const
     */
    "e": "e",

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown"
};



export default TitleElement;

