/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenFoodFactsOpenApi);
  }
}(this, function(expect, OpenFoodFactsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenFoodFactsOpenApi.WriteRequestsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WriteRequestsApi', function() {
    describe('getCgiProductImageCropPl', function() {
      it('should call getCgiProductImageCropPl successfully', function(done) {
        //uncomment below and update the code to test getCgiProductImageCropPl
        //instance.getCgiProductImageCropPl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCgiProductImageUploadPl', function() {
      it('should call getCgiProductImageUploadPl successfully', function(done) {
        //uncomment below and update the code to test getCgiProductImageUploadPl
        //instance.getCgiProductImageUploadPl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCgiProductImageCropPl', function() {
      it('should call postCgiProductImageCropPl successfully', function(done) {
        //uncomment below and update the code to test postCgiProductImageCropPl
        //instance.postCgiProductImageCropPl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCgiProductJqm2Pl', function() {
      it('should call postCgiProductJqm2Pl successfully', function(done) {
        //uncomment below and update the code to test postCgiProductJqm2Pl
        //instance.postCgiProductJqm2Pl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
