/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EcoscoreDataAdjustmentsProductionSystem } from './EcoscoreDataAdjustmentsProductionSystem';
import {
    EcoscoreDataAdjustmentsProductionSystemFromJSON,
    EcoscoreDataAdjustmentsProductionSystemFromJSONTyped,
    EcoscoreDataAdjustmentsProductionSystemToJSON,
} from './EcoscoreDataAdjustmentsProductionSystem';
import type { EcoscoreDataAdjustmentsPackaging } from './EcoscoreDataAdjustmentsPackaging';
import {
    EcoscoreDataAdjustmentsPackagingFromJSON,
    EcoscoreDataAdjustmentsPackagingFromJSONTyped,
    EcoscoreDataAdjustmentsPackagingToJSON,
} from './EcoscoreDataAdjustmentsPackaging';
import type { EcoscoreDataAdjustmentsOriginsOfIngredients } from './EcoscoreDataAdjustmentsOriginsOfIngredients';
import {
    EcoscoreDataAdjustmentsOriginsOfIngredientsFromJSON,
    EcoscoreDataAdjustmentsOriginsOfIngredientsFromJSONTyped,
    EcoscoreDataAdjustmentsOriginsOfIngredientsToJSON,
} from './EcoscoreDataAdjustmentsOriginsOfIngredients';
import type { EcoscoreDataAdjustmentsThreatenedSpecies } from './EcoscoreDataAdjustmentsThreatenedSpecies';
import {
    EcoscoreDataAdjustmentsThreatenedSpeciesFromJSON,
    EcoscoreDataAdjustmentsThreatenedSpeciesFromJSONTyped,
    EcoscoreDataAdjustmentsThreatenedSpeciesToJSON,
} from './EcoscoreDataAdjustmentsThreatenedSpecies';

/**
 * 
 * @export
 * @interface EcoscoreDataAdjustments
 */
export interface EcoscoreDataAdjustments {
    /**
     * 
     * @type {EcoscoreDataAdjustmentsOriginsOfIngredients}
     * @memberof EcoscoreDataAdjustments
     */
    originsOfIngredients?: EcoscoreDataAdjustmentsOriginsOfIngredients;
    /**
     * 
     * @type {EcoscoreDataAdjustmentsPackaging}
     * @memberof EcoscoreDataAdjustments
     */
    packaging?: EcoscoreDataAdjustmentsPackaging;
    /**
     * 
     * @type {EcoscoreDataAdjustmentsProductionSystem}
     * @memberof EcoscoreDataAdjustments
     */
    productionSystem?: EcoscoreDataAdjustmentsProductionSystem;
    /**
     * 
     * @type {EcoscoreDataAdjustmentsThreatenedSpecies}
     * @memberof EcoscoreDataAdjustments
     */
    threatenedSpecies?: EcoscoreDataAdjustmentsThreatenedSpecies;
}

/**
 * Check if a given object implements the EcoscoreDataAdjustments interface.
 */
export function instanceOfEcoscoreDataAdjustments(value: object): value is EcoscoreDataAdjustments {
    return true;
}

export function EcoscoreDataAdjustmentsFromJSON(json: any): EcoscoreDataAdjustments {
    return EcoscoreDataAdjustmentsFromJSONTyped(json, false);
}

export function EcoscoreDataAdjustmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EcoscoreDataAdjustments {
    if (json == null) {
        return json;
    }
    return {
        
        'originsOfIngredients': json['origins_of_ingredients'] == null ? undefined : EcoscoreDataAdjustmentsOriginsOfIngredientsFromJSON(json['origins_of_ingredients']),
        'packaging': json['packaging'] == null ? undefined : EcoscoreDataAdjustmentsPackagingFromJSON(json['packaging']),
        'productionSystem': json['production_system'] == null ? undefined : EcoscoreDataAdjustmentsProductionSystemFromJSON(json['production_system']),
        'threatenedSpecies': json['threatened_species'] == null ? undefined : EcoscoreDataAdjustmentsThreatenedSpeciesFromJSON(json['threatened_species']),
    };
}

export function EcoscoreDataAdjustmentsToJSON(value?: EcoscoreDataAdjustments | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'origins_of_ingredients': EcoscoreDataAdjustmentsOriginsOfIngredientsToJSON(value['originsOfIngredients']),
        'packaging': EcoscoreDataAdjustmentsPackagingToJSON(value['packaging']),
        'production_system': EcoscoreDataAdjustmentsProductionSystemToJSON(value['productionSystem']),
        'threatened_species': EcoscoreDataAdjustmentsThreatenedSpeciesToJSON(value['threatenedSpecies']),
    };
}

