/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAttributeGroups200ResponseInnerAttributesInner } from './GetAttributeGroups200ResponseInnerAttributesInner';
import {
    GetAttributeGroups200ResponseInnerAttributesInnerFromJSON,
    GetAttributeGroups200ResponseInnerAttributesInnerFromJSONTyped,
    GetAttributeGroups200ResponseInnerAttributesInnerToJSON,
} from './GetAttributeGroups200ResponseInnerAttributesInner';

/**
 * 
 * @export
 * @interface GetAttributeGroups200ResponseInner
 */
export interface GetAttributeGroups200ResponseInner {
    /**
     * unique id of the group
     * @type {string}
     * @memberof GetAttributeGroups200ResponseInner
     */
    id?: string;
    /**
     * Name of the group
     * @type {string}
     * @memberof GetAttributeGroups200ResponseInner
     */
    name?: string;
    /**
     * Attributes that are part of this group
     * 
     * @type {Array<GetAttributeGroups200ResponseInnerAttributesInner>}
     * @memberof GetAttributeGroups200ResponseInner
     */
    attributes?: Array<GetAttributeGroups200ResponseInnerAttributesInner>;
}

/**
 * Check if a given object implements the GetAttributeGroups200ResponseInner interface.
 */
export function instanceOfGetAttributeGroups200ResponseInner(value: object): value is GetAttributeGroups200ResponseInner {
    return true;
}

export function GetAttributeGroups200ResponseInnerFromJSON(json: any): GetAttributeGroups200ResponseInner {
    return GetAttributeGroups200ResponseInnerFromJSONTyped(json, false);
}

export function GetAttributeGroups200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAttributeGroups200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(GetAttributeGroups200ResponseInnerAttributesInnerFromJSON)),
    };
}

export function GetAttributeGroups200ResponseInnerToJSON(value?: GetAttributeGroups200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(GetAttributeGroups200ResponseInnerAttributesInnerToJSON)),
    };
}

