/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetProductBaseByBarcodeResponse } from './GetProductBaseByBarcodeResponse';
import {
    instanceOfGetProductBaseByBarcodeResponse,
    GetProductBaseByBarcodeResponseFromJSON,
    GetProductBaseByBarcodeResponseFromJSONTyped,
    GetProductBaseByBarcodeResponseToJSON,
} from './GetProductBaseByBarcodeResponse';
import type { GetProductKnowledgePanelsByBarcodeResponse } from './GetProductKnowledgePanelsByBarcodeResponse';
import {
    instanceOfGetProductKnowledgePanelsByBarcodeResponse,
    GetProductKnowledgePanelsByBarcodeResponseFromJSON,
    GetProductKnowledgePanelsByBarcodeResponseFromJSONTyped,
    GetProductKnowledgePanelsByBarcodeResponseToJSON,
} from './GetProductKnowledgePanelsByBarcodeResponse';

/**
 * @type GetProductByBarcodeResponse
 * 
 * @export
 */
export type GetProductByBarcodeResponse = GetProductBaseByBarcodeResponse | GetProductKnowledgePanelsByBarcodeResponse;

export function GetProductByBarcodeResponseFromJSON(json: any): GetProductByBarcodeResponse {
    return GetProductByBarcodeResponseFromJSONTyped(json, false);
}

export function GetProductByBarcodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProductByBarcodeResponse {
    if (json == null) {
        return json;
    }
    if (instanceOfGetProductBaseByBarcodeResponse(json)) {
        return GetProductBaseByBarcodeResponseFromJSONTyped(json, true);
    }
    if (instanceOfGetProductKnowledgePanelsByBarcodeResponse(json)) {
        return GetProductKnowledgePanelsByBarcodeResponseFromJSONTyped(json, true);
    }
}

export function GetProductByBarcodeResponseToJSON(value?: GetProductByBarcodeResponse | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfGetProductBaseByBarcodeResponse(value)) {
        return GetProductBaseByBarcodeResponseToJSON(value as GetProductBaseByBarcodeResponse);
    }
    if (instanceOfGetProductKnowledgePanelsByBarcodeResponse(value)) {
        return GetProductKnowledgePanelsByBarcodeResponseToJSON(value as GetProductKnowledgePanelsByBarcodeResponse);
    }

    return {};
}

