/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageSizesFull } from './ImageSizesFull';
import {
    ImageSizesFullFromJSON,
    ImageSizesFullFromJSONTyped,
    ImageSizesFullToJSON,
} from './ImageSizesFull';

/**
 * The available image sizes for the product (both reduced and full). 
 * The reduced images are the ones with numbers as the key( 100, 200 etc) 
 * while the full images have `full` as the key.
 * 
 * @export
 * @interface ImageSizes
 */
export interface ImageSizes {
    /**
     * 
     * @type {ImageSizesFull}
     * @memberof ImageSizes
     */
    full?: ImageSizesFull;
}

/**
 * Check if a given object implements the ImageSizes interface.
 */
export function instanceOfImageSizes(value: object): value is ImageSizes {
    return true;
}

export function ImageSizesFromJSON(json: any): ImageSizes {
    return ImageSizesFromJSONTyped(json, false);
}

export function ImageSizesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageSizes {
    if (json == null) {
        return json;
    }
    return {
        
        'full': json['full'] == null ? undefined : ImageSizesFullFromJSON(json['full']),
    };
}

export function ImageSizesToJSON(value?: ImageSizes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'full': ImageSizesFullToJSON(value['full']),
    };
}

