/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductImagesFrontSizes100
 */
export interface ProductImagesFrontSizes100 {
    /**
     * The height of the reduced/full image in pixels.
     * 
     * @type {number}
     * @memberof ProductImagesFrontSizes100
     */
    h?: number;
    /**
     * The width of the reduced/full image in pixels.
     * @type {number}
     * @memberof ProductImagesFrontSizes100
     */
    w?: number;
}

/**
 * Check if a given object implements the ProductImagesFrontSizes100 interface.
 */
export function instanceOfProductImagesFrontSizes100(value: object): value is ProductImagesFrontSizes100 {
    return true;
}

export function ProductImagesFrontSizes100FromJSON(json: any): ProductImagesFrontSizes100 {
    return ProductImagesFrontSizes100FromJSONTyped(json, false);
}

export function ProductImagesFrontSizes100FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImagesFrontSizes100 {
    if (json == null) {
        return json;
    }
    return {
        
        'h': json['h'] == null ? undefined : json['h'],
        'w': json['w'] == null ? undefined : json['w'],
    };
}

export function ProductImagesFrontSizes100ToJSON(value?: ProductImagesFrontSizes100 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'h': value['h'],
        'w': value['w'],
    };
}

