/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The recycling property is canonicalized using the packaging_recycling taxonomy.
 * @export
 * @interface PackagingComponentRecyclingInstruction
 */
export interface PackagingComponentRecyclingInstruction {
    /**
     * Canonical id of the entry in the taxonomy. If the value cannot be mapped to a taxonomy entry, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon.
     * @type {string}
     * @memberof PackagingComponentRecyclingInstruction
     */
    id?: string;
    /**
     * Name of the entry in the language requested in the tags_lc field of the request. This field is returned only of tags_lc is specified. If the translation is not available, or if the entry does not exist in the taxonomy, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon.
     * @type {string}
     * @memberof PackagingComponentRecyclingInstruction
     */
    lcName?: string;
}

/**
 * Check if a given object implements the PackagingComponentRecyclingInstruction interface.
 */
export function instanceOfPackagingComponentRecyclingInstruction(value: object): value is PackagingComponentRecyclingInstruction {
    return true;
}

export function PackagingComponentRecyclingInstructionFromJSON(json: any): PackagingComponentRecyclingInstruction {
    return PackagingComponentRecyclingInstructionFromJSONTyped(json, false);
}

export function PackagingComponentRecyclingInstructionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackagingComponentRecyclingInstruction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lcName': json['lc_name'] == null ? undefined : json['lc_name'],
    };
}

export function PackagingComponentRecyclingInstructionToJSON(value?: PackagingComponentRecyclingInstruction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'lc_name': value['lcName'],
    };
}

