/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: contact@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductMetaSourceFieldsOrgGs1 } from './ProductMetaSourceFieldsOrgGs1';
import {
    ProductMetaSourceFieldsOrgGs1FromJSON,
    ProductMetaSourceFieldsOrgGs1FromJSONTyped,
    ProductMetaSourceFieldsOrgGs1ToJSON,
} from './ProductMetaSourceFieldsOrgGs1';

/**
 * 
 * @export
 * @interface ProductMetaSourceFields
 */
export interface ProductMetaSourceFields {
    /**
     * 
     * @type {ProductMetaSourceFieldsOrgGs1}
     * @memberof ProductMetaSourceFields
     */
    orgGs1?: ProductMetaSourceFieldsOrgGs1;
}

/**
 * Check if a given object implements the ProductMetaSourceFields interface.
 */
export function instanceOfProductMetaSourceFields(value: object): value is ProductMetaSourceFields {
    return true;
}

export function ProductMetaSourceFieldsFromJSON(json: any): ProductMetaSourceFields {
    return ProductMetaSourceFieldsFromJSONTyped(json, false);
}

export function ProductMetaSourceFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductMetaSourceFields {
    if (json == null) {
        return json;
    }
    return {
        
        'orgGs1': json['org-gs1'] == null ? undefined : ProductMetaSourceFieldsOrgGs1FromJSON(json['org-gs1']),
    };
}

export function ProductMetaSourceFieldsToJSON(value?: ProductMetaSourceFields | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'org-gs1': ProductMetaSourceFieldsOrgGs1ToJSON(value['orgGs1']),
    };
}

