/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetProductByBarcodeKnowledgePanelsResponse from './GetProductByBarcodeKnowledgePanelsResponse';
import GetProductByBarcodeResponse from './GetProductByBarcodeResponse';
import ProductKnowledgePanels from './ProductKnowledgePanels';

/**
 * The GetProductByBarcodeAllResponse model module.
 * @module model/GetProductByBarcodeAllResponse
 * @version 2
 */
class GetProductByBarcodeAllResponse {
    /**
     * Constructs a new <code>GetProductByBarcodeAllResponse</code>.
     * @alias module:model/GetProductByBarcodeAllResponse
     * @param {(module:model/GetProductByBarcodeKnowledgePanelsResponse|module:model/GetProductByBarcodeResponse)} instance The actual instance to initialize GetProductByBarcodeAllResponse.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "GetProductByBarcodeResponse") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                GetProductByBarcodeResponse.validateJSON(instance); // throw an exception if no match
                // create GetProductByBarcodeResponse from JS object
                this.actualInstance = GetProductByBarcodeResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into GetProductByBarcodeResponse
            errorMessages.push("Failed to construct GetProductByBarcodeResponse: " + err)
        }

        try {
            if (typeof instance === "GetProductByBarcodeKnowledgePanelsResponse") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                GetProductByBarcodeKnowledgePanelsResponse.validateJSON(instance); // throw an exception if no match
                // create GetProductByBarcodeKnowledgePanelsResponse from JS object
                this.actualInstance = GetProductByBarcodeKnowledgePanelsResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into GetProductByBarcodeKnowledgePanelsResponse
            errorMessages.push("Failed to construct GetProductByBarcodeKnowledgePanelsResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `GetProductByBarcodeAllResponse` with oneOf schemas GetProductByBarcodeKnowledgePanelsResponse, GetProductByBarcodeResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `GetProductByBarcodeAllResponse` with oneOf schemas GetProductByBarcodeKnowledgePanelsResponse, GetProductByBarcodeResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>GetProductByBarcodeAllResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProductByBarcodeAllResponse} obj Optional instance to populate.
     * @return {module:model/GetProductByBarcodeAllResponse} The populated <code>GetProductByBarcodeAllResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        return new GetProductByBarcodeAllResponse(data);
    }

    /**
     * Gets the actual instance, which can be <code>GetProductByBarcodeKnowledgePanelsResponse</code>, <code>GetProductByBarcodeResponse</code>.
     * @return {(module:model/GetProductByBarcodeKnowledgePanelsResponse|module:model/GetProductByBarcodeResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>GetProductByBarcodeKnowledgePanelsResponse</code>, <code>GetProductByBarcodeResponse</code>.
     * @param {(module:model/GetProductByBarcodeKnowledgePanelsResponse|module:model/GetProductByBarcodeResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = GetProductByBarcodeAllResponse.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of GetProductByBarcodeAllResponse from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/GetProductByBarcodeAllResponse} An instance of GetProductByBarcodeAllResponse.
     */
    static fromJSON = function(json_string){
        return GetProductByBarcodeAllResponse.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * Barcode of the product (can be EAN-13 or internal codes for some food stores). For products without a barcode, Open Food Facts assigns a  number starting with the 200 reserved prefix. 
 * @member {String} code
 */
GetProductByBarcodeAllResponse.prototype['code'] = undefined;

/**
 * Return values based on ProductOpener/Display.pm analysis
 * @member {module:model/GetProductByBarcodeAllResponse.StatusEnum} status
 */
GetProductByBarcodeAllResponse.prototype['status'] = undefined;

/**
 * @member {String} status_verbose
 */
GetProductByBarcodeAllResponse.prototype['status_verbose'] = undefined;

/**
 * @member {module:model/ProductKnowledgePanels} product
 */
GetProductByBarcodeAllResponse.prototype['product'] = undefined;


GetProductByBarcodeAllResponse.OneOf = ["GetProductByBarcodeKnowledgePanelsResponse", "GetProductByBarcodeResponse"];

export default GetProductByBarcodeAllResponse;

