/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductKnowledgePanels from './ProductKnowledgePanels';

/**
 * The GetProductByBarcodeKnowledgePanelsResponse model module.
 * @module model/GetProductByBarcodeKnowledgePanelsResponse
 * @version 2
 */
class GetProductByBarcodeKnowledgePanelsResponse {
    /**
     * Constructs a new <code>GetProductByBarcodeKnowledgePanelsResponse</code>.
     * @alias module:model/GetProductByBarcodeKnowledgePanelsResponse
     */
    constructor() { 
        
        GetProductByBarcodeKnowledgePanelsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetProductByBarcodeKnowledgePanelsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProductByBarcodeKnowledgePanelsResponse} obj Optional instance to populate.
     * @return {module:model/GetProductByBarcodeKnowledgePanelsResponse} The populated <code>GetProductByBarcodeKnowledgePanelsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProductByBarcodeKnowledgePanelsResponse();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('status_verbose')) {
                obj['status_verbose'] = ApiClient.convertToType(data['status_verbose'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ProductKnowledgePanels.constructFromObject(data['product']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetProductByBarcodeKnowledgePanelsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProductByBarcodeKnowledgePanelsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['status_verbose'] && !(typeof data['status_verbose'] === 'string' || data['status_verbose'] instanceof String)) {
            throw new Error("Expected the field `status_verbose` to be a primitive type in the JSON string but got " + data['status_verbose']);
        }
        // validate the optional field `product`
        if (data['product']) { // data not null
          ProductKnowledgePanels.validateJSON(data['product']);
        }

        return true;
    }


}



/**
 * Barcode of the product (can be EAN-13 or internal codes for some food stores). For products without a barcode, Open Food Facts assigns a  number starting with the 200 reserved prefix. 
 * @member {String} code
 */
GetProductByBarcodeKnowledgePanelsResponse.prototype['code'] = undefined;

/**
 * Return values based on ProductOpener/Display.pm analysis
 * @member {module:model/GetProductByBarcodeKnowledgePanelsResponse.StatusEnum} status
 */
GetProductByBarcodeKnowledgePanelsResponse.prototype['status'] = undefined;

/**
 * @member {String} status_verbose
 */
GetProductByBarcodeKnowledgePanelsResponse.prototype['status_verbose'] = undefined;

/**
 * @member {module:model/ProductKnowledgePanels} product
 */
GetProductByBarcodeKnowledgePanelsResponse.prototype['product'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {Number}
 * @readonly
 */
GetProductByBarcodeKnowledgePanelsResponse['StatusEnum'] = {

    /**
     * value: 0
     * @const
     */
    "0": 0,

    /**
     * value: 1
     * @const
     */
    "1": 1
};



export default GetProductByBarcodeKnowledgePanelsResponse;

