/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductIngredientsPercentMax from './ProductIngredientsPercentMax';

/**
 * The Ingredient model module.
 * @module model/Ingredient
 * @version 2
 */
class Ingredient {
    /**
     * Constructs a new <code>Ingredient</code>.
     * @alias module:model/Ingredient
     */
    constructor() { 
        
        Ingredient.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Ingredient</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Ingredient} obj Optional instance to populate.
     * @return {module:model/Ingredient} The populated <code>Ingredient</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Ingredient();

            if (data.hasOwnProperty('ciqual_food_code')) {
                obj['ciqual_food_code'] = ApiClient.convertToType(data['ciqual_food_code'], 'String');
            }
            if (data.hasOwnProperty('ciqual_proxy_food_code')) {
                obj['ciqual_proxy_food_code'] = ApiClient.convertToType(data['ciqual_proxy_food_code'], 'String');
            }
            if (data.hasOwnProperty('ecobalyse_code')) {
                obj['ecobalyse_code'] = ApiClient.convertToType(data['ecobalyse_code'], 'String');
            }
            if (data.hasOwnProperty('from_palm_oil')) {
                obj['from_palm_oil'] = ApiClient.convertToType(data['from_palm_oil'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('ingredients')) {
                obj['ingredients'] = ApiClient.convertToType(data['ingredients'], [Ingredient]);
            }
            if (data.hasOwnProperty('percent')) {
                obj['percent'] = ApiClient.convertToType(data['percent'], 'Number');
            }
            if (data.hasOwnProperty('is_in_taxonomy')) {
                obj['is_in_taxonomy'] = ApiClient.convertToType(data['is_in_taxonomy'], 'Number');
            }
            if (data.hasOwnProperty('percent_estimate')) {
                obj['percent_estimate'] = ApiClient.convertToType(data['percent_estimate'], 'Number');
            }
            if (data.hasOwnProperty('percent_max')) {
                obj['percent_max'] = ProductIngredientsPercentMax.constructFromObject(data['percent_max']);
            }
            if (data.hasOwnProperty('percent_min')) {
                obj['percent_min'] = ApiClient.convertToType(data['percent_min'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('vegan')) {
                obj['vegan'] = ApiClient.convertToType(data['vegan'], 'String');
            }
            if (data.hasOwnProperty('vegetarian')) {
                obj['vegetarian'] = ApiClient.convertToType(data['vegetarian'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Ingredient</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Ingredient</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ciqual_food_code'] && !(typeof data['ciqual_food_code'] === 'string' || data['ciqual_food_code'] instanceof String)) {
            throw new Error("Expected the field `ciqual_food_code` to be a primitive type in the JSON string but got " + data['ciqual_food_code']);
        }
        // ensure the json data is a string
        if (data['ciqual_proxy_food_code'] && !(typeof data['ciqual_proxy_food_code'] === 'string' || data['ciqual_proxy_food_code'] instanceof String)) {
            throw new Error("Expected the field `ciqual_proxy_food_code` to be a primitive type in the JSON string but got " + data['ciqual_proxy_food_code']);
        }
        // ensure the json data is a string
        if (data['ecobalyse_code'] && !(typeof data['ecobalyse_code'] === 'string' || data['ecobalyse_code'] instanceof String)) {
            throw new Error("Expected the field `ecobalyse_code` to be a primitive type in the JSON string but got " + data['ecobalyse_code']);
        }
        // ensure the json data is a string
        if (data['from_palm_oil'] && !(typeof data['from_palm_oil'] === 'string' || data['from_palm_oil'] instanceof String)) {
            throw new Error("Expected the field `from_palm_oil` to be a primitive type in the JSON string but got " + data['from_palm_oil']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['ingredients']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ingredients'])) {
                throw new Error("Expected the field `ingredients` to be an array in the JSON data but got " + data['ingredients']);
            }
            // validate the optional field `ingredients` (array)
            for (const item of data['ingredients']) {
                Ingredient.validateJSON(item);
            };
        }
        // validate the optional field `percent_max`
        if (data['percent_max']) { // data not null
          ProductIngredientsPercentMax.validateJSON(data['percent_max']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['vegan'] && !(typeof data['vegan'] === 'string' || data['vegan'] instanceof String)) {
            throw new Error("Expected the field `vegan` to be a primitive type in the JSON string but got " + data['vegan']);
        }
        // ensure the json data is a string
        if (data['vegetarian'] && !(typeof data['vegetarian'] === 'string' || data['vegetarian'] instanceof String)) {
            throw new Error("Expected the field `vegetarian` to be a primitive type in the JSON string but got " + data['vegetarian']);
        }

        return true;
    }


}



/**
 * @member {String} ciqual_food_code
 */
Ingredient.prototype['ciqual_food_code'] = undefined;

/**
 * @member {String} ciqual_proxy_food_code
 */
Ingredient.prototype['ciqual_proxy_food_code'] = undefined;

/**
 * @member {String} ecobalyse_code
 */
Ingredient.prototype['ecobalyse_code'] = undefined;

/**
 * @member {String} from_palm_oil
 */
Ingredient.prototype['from_palm_oil'] = undefined;

/**
 * @member {String} id
 */
Ingredient.prototype['id'] = undefined;

/**
 * This structure gives the different ingredients and some information about them, like estimate on their quantity. 
 * @member {Array.<module:model/Ingredient>} ingredients
 */
Ingredient.prototype['ingredients'] = undefined;

/**
 * The percentage of the ingredient.
 * @member {Number} percent
 */
Ingredient.prototype['percent'] = undefined;

/**
 * @member {Number} is_in_taxonomy
 */
Ingredient.prototype['is_in_taxonomy'] = undefined;

/**
 * Estimated percentage of the ingredient.
 * @member {Number} percent_estimate
 */
Ingredient.prototype['percent_estimate'] = undefined;

/**
 * @member {module:model/ProductIngredientsPercentMax} percent_max
 */
Ingredient.prototype['percent_max'] = undefined;

/**
 * Minimum percentage of the ingredient.
 * @member {Number} percent_min
 */
Ingredient.prototype['percent_min'] = undefined;

/**
 * Text description of the ingredient.
 * @member {String} text
 */
Ingredient.prototype['text'] = undefined;

/**
 * Indicates if the ingredient is vegan.
 * @member {String} vegan
 */
Ingredient.prototype['vegan'] = undefined;

/**
 * Indicates if the ingredient is vegetarian.
 * @member {String} vegetarian
 */
Ingredient.prototype['vegetarian'] = undefined;






export default Ingredient;

