/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductTags model module.
 * @module model/ProductTags
 * @version 2
 */
class ProductTags {
    /**
     * Constructs a new <code>ProductTags</code>.
     * Data about a product which is represented as tags 
     * @alias module:model/ProductTags
     */
    constructor() { 
        
        ProductTags.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductTags</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductTags} obj Optional instance to populate.
     * @return {module:model/ProductTags} The populated <code>ProductTags</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductTags();

            if (data.hasOwnProperty('brands')) {
                obj['brands'] = ApiClient.convertToType(data['brands'], 'String');
            }
            if (data.hasOwnProperty('brands_tags')) {
                obj['brands_tags'] = ApiClient.convertToType(data['brands_tags'], ['String']);
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], 'String');
            }
            if (data.hasOwnProperty('categories_hierarchy')) {
                obj['categories_hierarchy'] = ApiClient.convertToType(data['categories_hierarchy'], ['String']);
            }
            if (data.hasOwnProperty('categories_lc')) {
                obj['categories_lc'] = ApiClient.convertToType(data['categories_lc'], 'String');
            }
            if (data.hasOwnProperty('categories_old')) {
                obj['categories_old'] = ApiClient.convertToType(data['categories_old'], 'String');
            }
            if (data.hasOwnProperty('categories_tags')) {
                obj['categories_tags'] = ApiClient.convertToType(data['categories_tags'], ['String']);
            }
            if (data.hasOwnProperty('checkers_tags')) {
                obj['checkers_tags'] = ApiClient.convertToType(data['checkers_tags'], ['String']);
            }
            if (data.hasOwnProperty('cities')) {
                obj['cities'] = ApiClient.convertToType(data['cities'], 'String');
            }
            if (data.hasOwnProperty('cities_tags')) {
                obj['cities_tags'] = ApiClient.convertToType(data['cities_tags'], [Object]);
            }
            if (data.hasOwnProperty('correctors_tags')) {
                obj['correctors_tags'] = ApiClient.convertToType(data['correctors_tags'], ['String']);
            }
            if (data.hasOwnProperty('countries')) {
                obj['countries'] = ApiClient.convertToType(data['countries'], 'String');
            }
            if (data.hasOwnProperty('countries_beforescanbot')) {
                obj['countries_beforescanbot'] = ApiClient.convertToType(data['countries_beforescanbot'], 'String');
            }
            if (data.hasOwnProperty('countries_hierarchy')) {
                obj['countries_hierarchy'] = ApiClient.convertToType(data['countries_hierarchy'], ['String']);
            }
            if (data.hasOwnProperty('countries_lc')) {
                obj['countries_lc'] = ApiClient.convertToType(data['countries_lc'], 'String');
            }
            if (data.hasOwnProperty('countries_tags')) {
                obj['countries_tags'] = ApiClient.convertToType(data['countries_tags'], ['String']);
            }
            if (data.hasOwnProperty('ecoscore_tags')) {
                obj['ecoscore_tags'] = ApiClient.convertToType(data['ecoscore_tags'], ['String']);
            }
            if (data.hasOwnProperty('emb_codes')) {
                obj['emb_codes'] = ApiClient.convertToType(data['emb_codes'], 'String');
            }
            if (data.hasOwnProperty('emb_codes_orig')) {
                obj['emb_codes_orig'] = ApiClient.convertToType(data['emb_codes_orig'], 'String');
            }
            if (data.hasOwnProperty('emb_codes_tags')) {
                obj['emb_codes_tags'] = ApiClient.convertToType(data['emb_codes_tags'], ['String']);
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], 'String');
            }
            if (data.hasOwnProperty('labels_hierarchy')) {
                obj['labels_hierarchy'] = ApiClient.convertToType(data['labels_hierarchy'], ['String']);
            }
            if (data.hasOwnProperty('labels_lc')) {
                obj['labels_lc'] = ApiClient.convertToType(data['labels_lc'], 'String');
            }
            if (data.hasOwnProperty('labels_tags')) {
                obj['labels_tags'] = ApiClient.convertToType(data['labels_tags'], ['String']);
            }
            if (data.hasOwnProperty('entry_dates_tags')) {
                obj['entry_dates_tags'] = ApiClient.convertToType(data['entry_dates_tags'], ['String']);
            }
            if (data.hasOwnProperty('manufacturing_places')) {
                obj['manufacturing_places'] = ApiClient.convertToType(data['manufacturing_places'], 'String');
            }
            if (data.hasOwnProperty('manufacturing_places_tags')) {
                obj['manufacturing_places_tags'] = ApiClient.convertToType(data['manufacturing_places_tags'], ['String']);
            }
            if (data.hasOwnProperty('nova_groups_tags')) {
                obj['nova_groups_tags'] = ApiClient.convertToType(data['nova_groups_tags'], ['String']);
            }
            if (data.hasOwnProperty('nutrient_levels_tags')) {
                obj['nutrient_levels_tags'] = ApiClient.convertToType(data['nutrient_levels_tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductTags</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductTags</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['brands'] && !(typeof data['brands'] === 'string' || data['brands'] instanceof String)) {
            throw new Error("Expected the field `brands` to be a primitive type in the JSON string but got " + data['brands']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['brands_tags'])) {
            throw new Error("Expected the field `brands_tags` to be an array in the JSON data but got " + data['brands_tags']);
        }
        // ensure the json data is a string
        if (data['categories'] && !(typeof data['categories'] === 'string' || data['categories'] instanceof String)) {
            throw new Error("Expected the field `categories` to be a primitive type in the JSON string but got " + data['categories']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['categories_hierarchy'])) {
            throw new Error("Expected the field `categories_hierarchy` to be an array in the JSON data but got " + data['categories_hierarchy']);
        }
        // ensure the json data is a string
        if (data['categories_lc'] && !(typeof data['categories_lc'] === 'string' || data['categories_lc'] instanceof String)) {
            throw new Error("Expected the field `categories_lc` to be a primitive type in the JSON string but got " + data['categories_lc']);
        }
        // ensure the json data is a string
        if (data['categories_old'] && !(typeof data['categories_old'] === 'string' || data['categories_old'] instanceof String)) {
            throw new Error("Expected the field `categories_old` to be a primitive type in the JSON string but got " + data['categories_old']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['categories_tags'])) {
            throw new Error("Expected the field `categories_tags` to be an array in the JSON data but got " + data['categories_tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['checkers_tags'])) {
            throw new Error("Expected the field `checkers_tags` to be an array in the JSON data but got " + data['checkers_tags']);
        }
        // ensure the json data is a string
        if (data['cities'] && !(typeof data['cities'] === 'string' || data['cities'] instanceof String)) {
            throw new Error("Expected the field `cities` to be a primitive type in the JSON string but got " + data['cities']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['cities_tags'])) {
            throw new Error("Expected the field `cities_tags` to be an array in the JSON data but got " + data['cities_tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['correctors_tags'])) {
            throw new Error("Expected the field `correctors_tags` to be an array in the JSON data but got " + data['correctors_tags']);
        }
        // ensure the json data is a string
        if (data['countries'] && !(typeof data['countries'] === 'string' || data['countries'] instanceof String)) {
            throw new Error("Expected the field `countries` to be a primitive type in the JSON string but got " + data['countries']);
        }
        // ensure the json data is a string
        if (data['countries_beforescanbot'] && !(typeof data['countries_beforescanbot'] === 'string' || data['countries_beforescanbot'] instanceof String)) {
            throw new Error("Expected the field `countries_beforescanbot` to be a primitive type in the JSON string but got " + data['countries_beforescanbot']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['countries_hierarchy'])) {
            throw new Error("Expected the field `countries_hierarchy` to be an array in the JSON data but got " + data['countries_hierarchy']);
        }
        // ensure the json data is a string
        if (data['countries_lc'] && !(typeof data['countries_lc'] === 'string' || data['countries_lc'] instanceof String)) {
            throw new Error("Expected the field `countries_lc` to be a primitive type in the JSON string but got " + data['countries_lc']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['countries_tags'])) {
            throw new Error("Expected the field `countries_tags` to be an array in the JSON data but got " + data['countries_tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ecoscore_tags'])) {
            throw new Error("Expected the field `ecoscore_tags` to be an array in the JSON data but got " + data['ecoscore_tags']);
        }
        // ensure the json data is a string
        if (data['emb_codes'] && !(typeof data['emb_codes'] === 'string' || data['emb_codes'] instanceof String)) {
            throw new Error("Expected the field `emb_codes` to be a primitive type in the JSON string but got " + data['emb_codes']);
        }
        // ensure the json data is a string
        if (data['emb_codes_orig'] && !(typeof data['emb_codes_orig'] === 'string' || data['emb_codes_orig'] instanceof String)) {
            throw new Error("Expected the field `emb_codes_orig` to be a primitive type in the JSON string but got " + data['emb_codes_orig']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['emb_codes_tags'])) {
            throw new Error("Expected the field `emb_codes_tags` to be an array in the JSON data but got " + data['emb_codes_tags']);
        }
        // ensure the json data is a string
        if (data['labels'] && !(typeof data['labels'] === 'string' || data['labels'] instanceof String)) {
            throw new Error("Expected the field `labels` to be a primitive type in the JSON string but got " + data['labels']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['labels_hierarchy'])) {
            throw new Error("Expected the field `labels_hierarchy` to be an array in the JSON data but got " + data['labels_hierarchy']);
        }
        // ensure the json data is a string
        if (data['labels_lc'] && !(typeof data['labels_lc'] === 'string' || data['labels_lc'] instanceof String)) {
            throw new Error("Expected the field `labels_lc` to be a primitive type in the JSON string but got " + data['labels_lc']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['labels_tags'])) {
            throw new Error("Expected the field `labels_tags` to be an array in the JSON data but got " + data['labels_tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['entry_dates_tags'])) {
            throw new Error("Expected the field `entry_dates_tags` to be an array in the JSON data but got " + data['entry_dates_tags']);
        }
        // ensure the json data is a string
        if (data['manufacturing_places'] && !(typeof data['manufacturing_places'] === 'string' || data['manufacturing_places'] instanceof String)) {
            throw new Error("Expected the field `manufacturing_places` to be a primitive type in the JSON string but got " + data['manufacturing_places']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['manufacturing_places_tags'])) {
            throw new Error("Expected the field `manufacturing_places_tags` to be an array in the JSON data but got " + data['manufacturing_places_tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['nova_groups_tags'])) {
            throw new Error("Expected the field `nova_groups_tags` to be an array in the JSON data but got " + data['nova_groups_tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['nutrient_levels_tags'])) {
            throw new Error("Expected the field `nutrient_levels_tags` to be an array in the JSON data but got " + data['nutrient_levels_tags']);
        }

        return true;
    }


}



/**
 * List of brands (not taxonomized)
 * @member {String} brands
 */
ProductTags.prototype['brands'] = undefined;

/**
 * @member {Array.<String>} brands_tags
 */
ProductTags.prototype['brands_tags'] = undefined;

/**
 * @member {String} categories
 */
ProductTags.prototype['categories'] = undefined;

/**
 * @member {Array.<String>} categories_hierarchy
 */
ProductTags.prototype['categories_hierarchy'] = undefined;

/**
 * Categories language code
 * @member {String} categories_lc
 */
ProductTags.prototype['categories_lc'] = undefined;

/**
 * @member {String} categories_old
 */
ProductTags.prototype['categories_old'] = undefined;

/**
 * @member {Array.<String>} categories_tags
 */
ProductTags.prototype['categories_tags'] = undefined;

/**
 * @member {Array.<String>} checkers_tags
 */
ProductTags.prototype['checkers_tags'] = undefined;

/**
 * @member {String} cities
 */
ProductTags.prototype['cities'] = undefined;

/**
 * @member {Array.<Object>} cities_tags
 */
ProductTags.prototype['cities_tags'] = undefined;

/**
 * @member {Array.<String>} correctors_tags
 */
ProductTags.prototype['correctors_tags'] = undefined;

/**
 * List of countries where the product is sold. 
 * @member {String} countries
 */
ProductTags.prototype['countries'] = undefined;

/**
 * @member {String} countries_beforescanbot
 */
ProductTags.prototype['countries_beforescanbot'] = undefined;

/**
 * @member {Array.<String>} countries_hierarchy
 */
ProductTags.prototype['countries_hierarchy'] = undefined;

/**
 * Countries language code
 * @member {String} countries_lc
 */
ProductTags.prototype['countries_lc'] = undefined;

/**
 * @member {Array.<String>} countries_tags
 */
ProductTags.prototype['countries_tags'] = undefined;

/**
 * All ecoscore of a product. Most of the time it's only one value, but it might eventually be more for products composed of sub-products. See also: `ecoscore_score`, `ecoscore_grade`. 
 * @member {Array.<String>} ecoscore_tags
 */
ProductTags.prototype['ecoscore_tags'] = undefined;

/**
 * Packager code. EMB is the French system of traceability codes for packager. 
 * @member {String} emb_codes
 */
ProductTags.prototype['emb_codes'] = undefined;

/**
 * @member {String} emb_codes_orig
 */
ProductTags.prototype['emb_codes_orig'] = undefined;

/**
 * @member {Array.<String>} emb_codes_tags
 */
ProductTags.prototype['emb_codes_tags'] = undefined;

/**
 * @member {String} labels
 */
ProductTags.prototype['labels'] = undefined;

/**
 * @member {Array.<String>} labels_hierarchy
 */
ProductTags.prototype['labels_hierarchy'] = undefined;

/**
 * @member {String} labels_lc
 */
ProductTags.prototype['labels_lc'] = undefined;

/**
 * @member {Array.<String>} labels_tags
 */
ProductTags.prototype['labels_tags'] = undefined;

/**
 * The data as a series of tag: `yyyy-mm-dd`, `yyyy-mm`, `yyyy` 
 * @member {Array.<String>} entry_dates_tags
 */
ProductTags.prototype['entry_dates_tags'] = undefined;

/**
 * Places where the product was manufactured or transformed. 
 * @member {String} manufacturing_places
 */
ProductTags.prototype['manufacturing_places'] = undefined;

/**
 * @member {Array.<String>} manufacturing_places_tags
 */
ProductTags.prototype['manufacturing_places_tags'] = undefined;

/**
 * @member {Array.<String>} nova_groups_tags
 */
ProductTags.prototype['nova_groups_tags'] = undefined;

/**
 * @member {Array.<String>} nutrient_levels_tags
 */
ProductTags.prototype['nutrient_levels_tags'] = undefined;






export default ProductTags;

