/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database.
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdjustmentsOriginOfIngredientAggregated } from "./AdjustmentsOriginOfIngredientAggregated";
import {
  AdjustmentsOriginOfIngredientAggregatedFromJSON,
  AdjustmentsOriginOfIngredientAggregatedFromJSONTyped,
  AdjustmentsOriginOfIngredientAggregatedToJSON,
  AdjustmentsOriginOfIngredientAggregatedToJSONTyped,
} from "./AdjustmentsOriginOfIngredientAggregated";

/**
 *
 * @export
 * @interface ProductEcoscoreAdjustmentsOriginsOfIngredients
 */
export interface ProductEcoscoreAdjustmentsOriginsOfIngredients {
  /**
   *
   * @type {Array<AdjustmentsOriginOfIngredientAggregated>}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  aggregated_origins?: Array<AdjustmentsOriginOfIngredientAggregated>;
  /**
   *
   * @type {number}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  epi_score?: number;
  /**
   *
   * @type {number}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  epi_value?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  origins_from_categories?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  origins_from_origins_field?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  transportation_score?: number;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  transportation_scores?: { [key: string]: number };
  /**
   *
   * @type {number}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  transportation_value?: number;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  transportation_values?: { [key: string]: number };
  /**
   *
   * @type {number}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  value?: number;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  values?: { [key: string]: number };
  /**
   *
   * @type {string}
   * @memberof ProductEcoscoreAdjustmentsOriginsOfIngredients
   */
  warning?: string;
}

/**
 * Check if a given object implements the ProductEcoscoreAdjustmentsOriginsOfIngredients interface.
 */
export function instanceOfProductEcoscoreAdjustmentsOriginsOfIngredients(
  value: object,
): value is ProductEcoscoreAdjustmentsOriginsOfIngredients {
  return true;
}

export function ProductEcoscoreAdjustmentsOriginsOfIngredientsFromJSON(
  json: any,
): ProductEcoscoreAdjustmentsOriginsOfIngredients {
  return ProductEcoscoreAdjustmentsOriginsOfIngredientsFromJSONTyped(
    json,
    false,
  );
}

export function ProductEcoscoreAdjustmentsOriginsOfIngredientsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProductEcoscoreAdjustmentsOriginsOfIngredients {
  if (json == null) {
    return json;
  }
  return {
    aggregated_origins:
      json["aggregated_origins"] == null
        ? undefined
        : (json["aggregated_origins"] as Array<any>).map(
            AdjustmentsOriginOfIngredientAggregatedFromJSON,
          ),
    epi_score: json["epi_score"] == null ? undefined : json["epi_score"],
    epi_value: json["epi_value"] == null ? undefined : json["epi_value"],
    origins_from_categories:
      json["origins_from_categories"] == null
        ? undefined
        : json["origins_from_categories"],
    origins_from_origins_field:
      json["origins_from_origins_field"] == null
        ? undefined
        : json["origins_from_origins_field"],
    transportation_score:
      json["transportation_score"] == null
        ? undefined
        : json["transportation_score"],
    transportation_scores:
      json["transportation_scores"] == null
        ? undefined
        : json["transportation_scores"],
    transportation_value:
      json["transportation_value"] == null
        ? undefined
        : json["transportation_value"],
    transportation_values:
      json["transportation_values"] == null
        ? undefined
        : json["transportation_values"],
    value: json["value"] == null ? undefined : json["value"],
    values: json["values"] == null ? undefined : json["values"],
    warning: json["warning"] == null ? undefined : json["warning"],
  };
}

export function ProductEcoscoreAdjustmentsOriginsOfIngredientsToJSON(
  json: any,
): ProductEcoscoreAdjustmentsOriginsOfIngredients {
  return ProductEcoscoreAdjustmentsOriginsOfIngredientsToJSONTyped(json, false);
}

export function ProductEcoscoreAdjustmentsOriginsOfIngredientsToJSONTyped(
  value?: ProductEcoscoreAdjustmentsOriginsOfIngredients | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    aggregated_origins:
      value["aggregated_origins"] == null
        ? undefined
        : (value["aggregated_origins"] as Array<any>).map(
            AdjustmentsOriginOfIngredientAggregatedToJSON,
          ),
    epi_score: value["epi_score"],
    epi_value: value["epi_value"],
    origins_from_categories: value["origins_from_categories"],
    origins_from_origins_field: value["origins_from_origins_field"],
    transportation_score: value["transportation_score"],
    transportation_scores: value["transportation_scores"],
    transportation_value: value["transportation_value"],
    transportation_values: value["transportation_values"],
    value: value["value"],
    values: value["values"],
    warning: value["warning"],
  };
}
