/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database.
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Ingredient } from "./Ingredient";
import {
  IngredientFromJSON,
  IngredientFromJSONTyped,
  IngredientToJSON,
  IngredientToJSONTyped,
} from "./Ingredient";
import type { NumberStringObjectType } from "./NumberStringObjectType";
import {
  NumberStringObjectTypeFromJSON,
  NumberStringObjectTypeFromJSONTyped,
  NumberStringObjectTypeToJSON,
  NumberStringObjectTypeToJSONTyped,
} from "./NumberStringObjectType";
import type { ProductIngredientsIngredientsAnalysis } from "./ProductIngredientsIngredientsAnalysis";
import {
  ProductIngredientsIngredientsAnalysisFromJSON,
  ProductIngredientsIngredientsAnalysisFromJSONTyped,
  ProductIngredientsIngredientsAnalysisToJSON,
  ProductIngredientsIngredientsAnalysisToJSONTyped,
} from "./ProductIngredientsIngredientsAnalysis";

/**
 * Fields about ingredients of a product
 * @export
 * @interface ProductIngredients
 */
export interface ProductIngredients {
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  additives_tags?: Array<string>;
  /**
   * comma separated list of allergens
   * @type {string}
   * @memberof ProductIngredients
   */
  allergens?: string;
  /**
   * language in which `allergens` where input
   * @type {string}
   * @memberof ProductIngredients
   */
  allergens_lc?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  allergens_hierarchy?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  allergens_tags?: Array<string>;
  /**
   * This structure gives the different ingredients and some information about them,
   * like estimate on their quantity.
   *
   * @type {Array<Ingredient>}
   * @memberof ProductIngredients
   */
  ingredients?: Array<Ingredient>;
  /**
   *
   * @type {ProductIngredientsIngredientsAnalysis}
   * @memberof ProductIngredients
   */
  ingredients_analysis?: ProductIngredientsIngredientsAnalysis;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  ingredients_analysis_tags?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_from_or_that_may_be_from_palm_oil_n?: number;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_from_palm_oil_n?: number;
  /**
   *
   * @type {Array<object>}
   * @memberof ProductIngredients
   */
  ingredients_from_palm_oil_tags?: Array<object>;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  ingredients_hierarchy?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_n?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  ingredients_n_tags?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  ingredients_original_tags?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_percent_analysis?: number;
  /**
   * Number of sweeteners additives in the ingredients. Undefined if ingredients are not specified.
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_sweeteners_n?: number;
  /**
   * Number of non-nutritive sweeteners additives (as specified in the Nutri-Score formula) in the ingredients. Undefined if ingredients are not specified.
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_non_nutritive_sweeteners_n?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductIngredients
   */
  ingredients_tags?: Array<string>;
  /**
   * Language that was used to parse the ingredient list. If `ingredients_text` is available
   * for the product main language (`lang`), `ingredients_lc=lang`, otherwise we look at
   * `ingredients_text` fields for other languages and set `ingredients_lc` to the first
   * non-empty `ingredient_text`.
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  ingredients_lc?: string;
  /**
   * Ingredients text in Italian
   * @type {string}
   * @memberof ProductIngredients
   */
  ingredients_text_it?: string;
  /**
   * Ingredients text in English
   * @type {string}
   * @memberof ProductIngredients
   */
  ingredients_text_en?: string;
  /**
   * Raw list of ingredients. This will get automatically
   * parsed and get used to compute the Eco-Score or find allergens, etc..
   *
   * It's a copy of ingredients_text in the main language of the product (see `lang` proprety).
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  ingredients_text?: string;
  /**
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  ingredients_text_with_allergens?: string;
  /**
   * Same text as `ingredients_text` but where allergens have HTML elements around them to identify them
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  ingredients_text_with_allergens_it?: string;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_that_may_be_from_palm_oil_n?: number;
  /**
   *
   * @type {Array<object>}
   * @memberof ProductIngredients
   */
  ingredients_that_may_be_from_palm_oil_tags?: Array<object>;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_with_specified_percent_n?: number;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_with_specified_percent_sum?: number;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_with_unspecified_percent_n?: number;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  ingredients_with_unspecified_percent_sum?: number;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  known_ingredients_n?: number;
  /**
   * Origins of ingredients
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  origins?: string;
  /**
   *
   * @type {Array<object>}
   * @memberof ProductIngredients
   */
  origins_hierarchy?: Array<object>;
  /**
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  origins_lc?: string;
  /**
   *
   * @type {Array<object>}
   * @memberof ProductIngredients
   */
  origins_tags?: Array<object>;
  /**
   * List of substances that might cause allergies
   * that are present in trace amounts in the product
   * (this does not include the ingredients, as they
   * are not only present in trace amounts).
   * It is taxonomized with the allergens taxonomy.
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  traces?: string;
  /**
   *
   * @type {Array<NumberStringObjectType>}
   * @memberof ProductIngredients
   */
  traces_hierarchy?: Array<NumberStringObjectType>;
  /**
   *
   * @type {string}
   * @memberof ProductIngredients
   */
  traces_lc?: string;
  /**
   *
   * @type {Array<NumberStringObjectType>}
   * @memberof ProductIngredients
   */
  traces_tags?: Array<NumberStringObjectType>;
  /**
   *
   * @type {number}
   * @memberof ProductIngredients
   */
  unknown_ingredients_n?: number;
}

/**
 * Check if a given object implements the ProductIngredients interface.
 */
export function instanceOfProductIngredients(
  value: object,
): value is ProductIngredients {
  return true;
}

export function ProductIngredientsFromJSON(json: any): ProductIngredients {
  return ProductIngredientsFromJSONTyped(json, false);
}

export function ProductIngredientsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProductIngredients {
  if (json == null) {
    return json;
  }
  return {
    additives_tags:
      json["additives_tags"] == null ? undefined : json["additives_tags"],
    allergens: json["allergens"] == null ? undefined : json["allergens"],
    allergens_lc:
      json["allergens_lc"] == null ? undefined : json["allergens_lc"],
    allergens_hierarchy:
      json["allergens_hierarchy"] == null
        ? undefined
        : json["allergens_hierarchy"],
    allergens_tags:
      json["allergens_tags"] == null ? undefined : json["allergens_tags"],
    ingredients:
      json["ingredients"] == null
        ? undefined
        : (json["ingredients"] as Array<any>).map(IngredientFromJSON),
    ingredients_analysis:
      json["ingredients_analysis"] == null
        ? undefined
        : ProductIngredientsIngredientsAnalysisFromJSON(
            json["ingredients_analysis"],
          ),
    ingredients_analysis_tags:
      json["ingredients_analysis_tags"] == null
        ? undefined
        : json["ingredients_analysis_tags"],
    ingredients_from_or_that_may_be_from_palm_oil_n:
      json["ingredients_from_or_that_may_be_from_palm_oil_n"] == null
        ? undefined
        : json["ingredients_from_or_that_may_be_from_palm_oil_n"],
    ingredients_from_palm_oil_n:
      json["ingredients_from_palm_oil_n"] == null
        ? undefined
        : json["ingredients_from_palm_oil_n"],
    ingredients_from_palm_oil_tags:
      json["ingredients_from_palm_oil_tags"] == null
        ? undefined
        : json["ingredients_from_palm_oil_tags"],
    ingredients_hierarchy:
      json["ingredients_hierarchy"] == null
        ? undefined
        : json["ingredients_hierarchy"],
    ingredients_n:
      json["ingredients_n"] == null ? undefined : json["ingredients_n"],
    ingredients_n_tags:
      json["ingredients_n_tags"] == null
        ? undefined
        : json["ingredients_n_tags"],
    ingredients_original_tags:
      json["ingredients_original_tags"] == null
        ? undefined
        : json["ingredients_original_tags"],
    ingredients_percent_analysis:
      json["ingredients_percent_analysis"] == null
        ? undefined
        : json["ingredients_percent_analysis"],
    ingredients_sweeteners_n:
      json["ingredients_sweeteners_n"] == null
        ? undefined
        : json["ingredients_sweeteners_n"],
    ingredients_non_nutritive_sweeteners_n:
      json["ingredients_non_nutritive_sweeteners_n"] == null
        ? undefined
        : json["ingredients_non_nutritive_sweeteners_n"],
    ingredients_tags:
      json["ingredients_tags"] == null ? undefined : json["ingredients_tags"],
    ingredients_lc:
      json["ingredients_lc"] == null ? undefined : json["ingredients_lc"],
    ingredients_text_it:
      json["ingredients_text_it"] == null
        ? undefined
        : json["ingredients_text_it"],
    ingredients_text_en:
      json["ingredients_text_en"] == null
        ? undefined
        : json["ingredients_text_en"],
    ingredients_text:
      json["ingredients_text"] == null ? undefined : json["ingredients_text"],
    ingredients_text_with_allergens:
      json["ingredients_text_with_allergens"] == null
        ? undefined
        : json["ingredients_text_with_allergens"],
    ingredients_text_with_allergens_it:
      json["ingredients_text_with_allergens_it"] == null
        ? undefined
        : json["ingredients_text_with_allergens_it"],
    ingredients_that_may_be_from_palm_oil_n:
      json["ingredients_that_may_be_from_palm_oil_n"] == null
        ? undefined
        : json["ingredients_that_may_be_from_palm_oil_n"],
    ingredients_that_may_be_from_palm_oil_tags:
      json["ingredients_that_may_be_from_palm_oil_tags"] == null
        ? undefined
        : json["ingredients_that_may_be_from_palm_oil_tags"],
    ingredients_with_specified_percent_n:
      json["ingredients_with_specified_percent_n"] == null
        ? undefined
        : json["ingredients_with_specified_percent_n"],
    ingredients_with_specified_percent_sum:
      json["ingredients_with_specified_percent_sum"] == null
        ? undefined
        : json["ingredients_with_specified_percent_sum"],
    ingredients_with_unspecified_percent_n:
      json["ingredients_with_unspecified_percent_n"] == null
        ? undefined
        : json["ingredients_with_unspecified_percent_n"],
    ingredients_with_unspecified_percent_sum:
      json["ingredients_with_unspecified_percent_sum"] == null
        ? undefined
        : json["ingredients_with_unspecified_percent_sum"],
    known_ingredients_n:
      json["known_ingredients_n"] == null
        ? undefined
        : json["known_ingredients_n"],
    origins: json["origins"] == null ? undefined : json["origins"],
    origins_hierarchy:
      json["origins_hierarchy"] == null ? undefined : json["origins_hierarchy"],
    origins_lc: json["origins_lc"] == null ? undefined : json["origins_lc"],
    origins_tags:
      json["origins_tags"] == null ? undefined : json["origins_tags"],
    traces: json["traces"] == null ? undefined : json["traces"],
    traces_hierarchy:
      json["traces_hierarchy"] == null
        ? undefined
        : (json["traces_hierarchy"] as Array<any>).map(
            NumberStringObjectTypeFromJSON,
          ),
    traces_lc: json["traces_lc"] == null ? undefined : json["traces_lc"],
    traces_tags:
      json["traces_tags"] == null
        ? undefined
        : (json["traces_tags"] as Array<any>).map(
            NumberStringObjectTypeFromJSON,
          ),
    unknown_ingredients_n:
      json["unknown_ingredients_n"] == null
        ? undefined
        : json["unknown_ingredients_n"],
  };
}

export function ProductIngredientsToJSON(json: any): ProductIngredients {
  return ProductIngredientsToJSONTyped(json, false);
}

export function ProductIngredientsToJSONTyped(
  value?: ProductIngredients | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    additives_tags: value["additives_tags"],
    allergens: value["allergens"],
    allergens_lc: value["allergens_lc"],
    allergens_hierarchy: value["allergens_hierarchy"],
    allergens_tags: value["allergens_tags"],
    ingredients:
      value["ingredients"] == null
        ? undefined
        : (value["ingredients"] as Array<any>).map(IngredientToJSON),
    ingredients_analysis: ProductIngredientsIngredientsAnalysisToJSON(
      value["ingredients_analysis"],
    ),
    ingredients_analysis_tags: value["ingredients_analysis_tags"],
    ingredients_from_or_that_may_be_from_palm_oil_n:
      value["ingredients_from_or_that_may_be_from_palm_oil_n"],
    ingredients_from_palm_oil_n: value["ingredients_from_palm_oil_n"],
    ingredients_from_palm_oil_tags: value["ingredients_from_palm_oil_tags"],
    ingredients_hierarchy: value["ingredients_hierarchy"],
    ingredients_n: value["ingredients_n"],
    ingredients_n_tags: value["ingredients_n_tags"],
    ingredients_original_tags: value["ingredients_original_tags"],
    ingredients_percent_analysis: value["ingredients_percent_analysis"],
    ingredients_sweeteners_n: value["ingredients_sweeteners_n"],
    ingredients_non_nutritive_sweeteners_n:
      value["ingredients_non_nutritive_sweeteners_n"],
    ingredients_tags: value["ingredients_tags"],
    ingredients_lc: value["ingredients_lc"],
    ingredients_text_it: value["ingredients_text_it"],
    ingredients_text_en: value["ingredients_text_en"],
    ingredients_text: value["ingredients_text"],
    ingredients_text_with_allergens: value["ingredients_text_with_allergens"],
    ingredients_text_with_allergens_it:
      value["ingredients_text_with_allergens_it"],
    ingredients_that_may_be_from_palm_oil_n:
      value["ingredients_that_may_be_from_palm_oil_n"],
    ingredients_that_may_be_from_palm_oil_tags:
      value["ingredients_that_may_be_from_palm_oil_tags"],
    ingredients_with_specified_percent_n:
      value["ingredients_with_specified_percent_n"],
    ingredients_with_specified_percent_sum:
      value["ingredients_with_specified_percent_sum"],
    ingredients_with_unspecified_percent_n:
      value["ingredients_with_unspecified_percent_n"],
    ingredients_with_unspecified_percent_sum:
      value["ingredients_with_unspecified_percent_sum"],
    known_ingredients_n: value["known_ingredients_n"],
    origins: value["origins"],
    origins_hierarchy: value["origins_hierarchy"],
    origins_lc: value["origins_lc"],
    origins_tags: value["origins_tags"],
    traces: value["traces"],
    traces_hierarchy:
      value["traces_hierarchy"] == null
        ? undefined
        : (value["traces_hierarchy"] as Array<any>).map(
            NumberStringObjectTypeToJSON,
          ),
    traces_lc: value["traces_lc"],
    traces_tags:
      value["traces_tags"] == null
        ? undefined
        : (value["traces_tags"] as Array<any>).map(
            NumberStringObjectTypeToJSON,
          ),
    unknown_ingredients_n: value["unknown_ingredients_n"],
  };
}
