/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database.
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RotateAPhotoResponseImage
 */
export interface RotateAPhotoResponseImage {
  /**
   *
   * @type {string}
   * @memberof RotateAPhotoResponseImage
   */
  display_url?: string;
}

/**
 * Check if a given object implements the RotateAPhotoResponseImage interface.
 */
export function instanceOfRotateAPhotoResponseImage(
  value: object,
): value is RotateAPhotoResponseImage {
  return true;
}

export function RotateAPhotoResponseImageFromJSON(
  json: any,
): RotateAPhotoResponseImage {
  return RotateAPhotoResponseImageFromJSONTyped(json, false);
}

export function RotateAPhotoResponseImageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RotateAPhotoResponseImage {
  if (json == null) {
    return json;
  }
  return {
    display_url: json["display_url"] == null ? undefined : json["display_url"],
  };
}

export function RotateAPhotoResponseImageToJSON(
  json: any,
): RotateAPhotoResponseImage {
  return RotateAPhotoResponseImageToJSONTyped(json, false);
}

export function RotateAPhotoResponseImageToJSONTyped(
  value?: RotateAPhotoResponseImage | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    display_url: value["display_url"],
  };
}
