/* tslint:disable */
/* eslint-disable */
/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database.
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TableColumn
 */
export interface TableColumn {
  /**
   *
   * @type {string}
   * @memberof TableColumn
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof TableColumn
   */
  text?: string;
  /**
   *
   * @type {string}
   * @memberof TableColumn
   */
  text_for_small_screens?: string;
  /**
   *
   * @type {string}
   * @memberof TableColumn
   */
  style?: string;
  /**
   *
   * @type {string}
   * @memberof TableColumn
   */
  column_group_id?: string;
  /**
   *
   * @type {boolean}
   * @memberof TableColumn
   */
  shown_by_default?: boolean;
}

/**
 * Check if a given object implements the TableColumn interface.
 */
export function instanceOfTableColumn(value: object): value is TableColumn {
  return true;
}

export function TableColumnFromJSON(json: any): TableColumn {
  return TableColumnFromJSONTyped(json, false);
}

export function TableColumnFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableColumn {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"] == null ? undefined : json["type"],
    text: json["text"] == null ? undefined : json["text"],
    text_for_small_screens:
      json["text_for_small_screens"] == null
        ? undefined
        : json["text_for_small_screens"],
    style: json["style"] == null ? undefined : json["style"],
    column_group_id:
      json["column_group_id"] == null ? undefined : json["column_group_id"],
    shown_by_default:
      json["shown_by_default"] == null ? undefined : json["shown_by_default"],
  };
}

export function TableColumnToJSON(json: any): TableColumn {
  return TableColumnToJSONTyped(json, false);
}

export function TableColumnToJSONTyped(
  value?: TableColumn | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    text: value["text"],
    text_for_small_screens: value["text_for_small_screens"],
    style: value["style"],
    column_group_id: value["column_group_id"],
    shown_by_default: value["shown_by_default"],
  };
}
