/**
 * Open Food Facts Open API
 * As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. 
 *
 * The version of the OpenAPI document: 2
 * Contact: reuse@openfoodfacts.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddOrEditAProductResponse from './model/AddOrEditAProductResponse';
import AddPhotoToExistingProductResponse from './model/AddPhotoToExistingProductResponse';
import AddPhotoToExistingProductResponseFilesInner from './model/AddPhotoToExistingProductResponseFilesInner';
import AddPhotoToExistingProductResponseImage from './model/AddPhotoToExistingProductResponseImage';
import AdjustmentsOriginOfIngredientAggregated from './model/AdjustmentsOriginOfIngredientAggregated';
import AdjustmentsPackagingItem from './model/AdjustmentsPackagingItem';
import AppCredentials from './model/AppCredentials';
import Attribute from './model/Attribute';
import AttributeGroup from './model/AttributeGroup';
import Element from './model/Element';
import GetPreferences200ResponseInner from './model/GetPreferences200ResponseInner';
import GetProductByBarcodeAllResponse from './model/GetProductByBarcodeAllResponse';
import GetProductByBarcodeKnowledgePanelsResponse from './model/GetProductByBarcodeKnowledgePanelsResponse';
import GetProductByBarcodeResponse from './model/GetProductByBarcodeResponse';
import Image from './model/Image';
import ImageElement from './model/ImageElement';
import ImageRole from './model/ImageRole';
import ImageRoleSizes from './model/ImageRoleSizes';
import ImageSize from './model/ImageSize';
import ImageSizes from './model/ImageSizes';
import Ingredient from './model/Ingredient';
import IngredientPercentMax from './model/IngredientPercentMax';
import NumberStringObjectType from './model/NumberStringObjectType';
import Nutrient from './model/Nutrient';
import Nutriscore2021 from './model/Nutriscore2021';
import Nutriscore20211 from './model/Nutriscore20211';
import Nutriscore2021Data from './model/Nutriscore2021Data';
import Nutriscore2021Data1 from './model/Nutriscore2021Data1';
import Nutriscore2023 from './model/Nutriscore2023';
import Nutriscore20231 from './model/Nutriscore20231';
import Nutriscore2023Data from './model/Nutriscore2023Data';
import Nutriscore2023DataComponents from './model/Nutriscore2023DataComponents';
import NutriscoreComponent from './model/NutriscoreComponent';
import Nutriscores from './model/Nutriscores';
import Nutriscores1 from './model/Nutriscores1';
import OcrOnProductResponse from './model/OcrOnProductResponse';
import PackagingComponentREAD from './model/PackagingComponentREAD';
import Panel from './model/Panel';
import PanelElement from './model/PanelElement';
import PanelGroupElement from './model/PanelGroupElement';
import Panels from './model/Panels';
import Product from './model/Product';
import ProductAllOfManufacturer from './model/ProductAllOfManufacturer';
import ProductAttributeGroup from './model/ProductAttributeGroup';
import ProductAttributeGroups from './model/ProductAttributeGroups';
import ProductBase from './model/ProductBase';
import ProductEcoScore from './model/ProductEcoScore';
import ProductEcoscoreAdjustments from './model/ProductEcoscoreAdjustments';
import ProductEcoscoreAdjustmentsOriginsOfIngredients from './model/ProductEcoscoreAdjustmentsOriginsOfIngredients';
import ProductEcoscoreAdjustmentsPackaging from './model/ProductEcoscoreAdjustmentsPackaging';
import ProductEcoscoreAdjustmentsProductionSystem from './model/ProductEcoscoreAdjustmentsProductionSystem';
import ProductEcoscoreAdjustmentsThreatenedSpecies from './model/ProductEcoscoreAdjustmentsThreatenedSpecies';
import ProductEcoscoreData from './model/ProductEcoscoreData';
import ProductEcoscoreDataAgribalyse from './model/ProductEcoscoreDataAgribalyse';
import ProductEcoscoreDataMissing from './model/ProductEcoscoreDataMissing';
import ProductEcoscoreDataPreviousData from './model/ProductEcoscoreDataPreviousData';
import ProductExtended from './model/ProductExtended';
import ProductExtendedCategoriesProperties from './model/ProductExtendedCategoriesProperties';
import ProductExtendedOwnerFields from './model/ProductExtendedOwnerFields';
import ProductImages from './model/ProductImages';
import ProductImagesProperties from './model/ProductImagesProperties';
import ProductIngredients from './model/ProductIngredients';
import ProductIngredientsIngredientsAnalysis from './model/ProductIngredientsIngredientsAnalysis';
import ProductIngredientsPercentMax from './model/ProductIngredientsPercentMax';
import ProductKnowledgePanels from './model/ProductKnowledgePanels';
import ProductMetaSource from './model/ProductMetaSource';
import ProductMetaSourceFields from './model/ProductMetaSourceFields';
import ProductMetaSourceFieldsOrgGs from './model/ProductMetaSourceFieldsOrgGs';
import ProductMetaSourceManufacturer from './model/ProductMetaSourceManufacturer';
import ProductMetadata from './model/ProductMetadata';
import ProductMisc from './model/ProductMisc';
import ProductMiscNutrientLevels from './model/ProductMiscNutrientLevels';
import ProductNutriscore from './model/ProductNutriscore';
import ProductNutrition from './model/ProductNutrition';
import ProductNutritionNutriments from './model/ProductNutritionNutriments';
import ProductNutritionNutriscoreData from './model/ProductNutritionNutriscoreData';
import ProductQuality from './model/ProductQuality';
import ProductSelectedImages from './model/ProductSelectedImages';
import ProductSelectedImagesIngredients from './model/ProductSelectedImagesIngredients';
import ProductTags from './model/ProductTags';
import RotateAPhotoResponse from './model/RotateAPhotoResponse';
import RotateAPhotoResponseImage from './model/RotateAPhotoResponseImage';
import SearchForProductsResponse from './model/SearchForProductsResponse';
import TableColumn from './model/TableColumn';
import TableElement from './model/TableElement';
import TextElement from './model/TextElement';
import TitleElement from './model/TitleElement';
import UnselectAPhotoResponse from './model/UnselectAPhotoResponse';
import AuthenticationApi from './api/AuthenticationApi';
import AuxiliaryOperationsApi from './api/AuxiliaryOperationsApi';
import PersonalSearchApi from './api/PersonalSearchApi';
import ReadRequestsApi from './api/ReadRequestsApi';
import WriteRequestsApi from './api/WriteRequestsApi';


/**
* As a developer, the Open Food Facts API allows you to get information and contribute to the products database. You can create great apps to help people make better food choices and also provide data to enhance the database. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenFoodFactsOpenApi = require('index'); // See note below*.
* var xxxSvc = new OpenFoodFactsOpenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenFoodFactsOpenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenFoodFactsOpenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenFoodFactsOpenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddOrEditAProductResponse model constructor.
     * @property {module:model/AddOrEditAProductResponse}
     */
    AddOrEditAProductResponse,

    /**
     * The AddPhotoToExistingProductResponse model constructor.
     * @property {module:model/AddPhotoToExistingProductResponse}
     */
    AddPhotoToExistingProductResponse,

    /**
     * The AddPhotoToExistingProductResponseFilesInner model constructor.
     * @property {module:model/AddPhotoToExistingProductResponseFilesInner}
     */
    AddPhotoToExistingProductResponseFilesInner,

    /**
     * The AddPhotoToExistingProductResponseImage model constructor.
     * @property {module:model/AddPhotoToExistingProductResponseImage}
     */
    AddPhotoToExistingProductResponseImage,

    /**
     * The AdjustmentsOriginOfIngredientAggregated model constructor.
     * @property {module:model/AdjustmentsOriginOfIngredientAggregated}
     */
    AdjustmentsOriginOfIngredientAggregated,

    /**
     * The AdjustmentsPackagingItem model constructor.
     * @property {module:model/AdjustmentsPackagingItem}
     */
    AdjustmentsPackagingItem,

    /**
     * The AppCredentials model constructor.
     * @property {module:model/AppCredentials}
     */
    AppCredentials,

    /**
     * The Attribute model constructor.
     * @property {module:model/Attribute}
     */
    Attribute,

    /**
     * The AttributeGroup model constructor.
     * @property {module:model/AttributeGroup}
     */
    AttributeGroup,

    /**
     * The Element model constructor.
     * @property {module:model/Element}
     */
    Element,

    /**
     * The GetPreferences200ResponseInner model constructor.
     * @property {module:model/GetPreferences200ResponseInner}
     */
    GetPreferences200ResponseInner,

    /**
     * The GetProductByBarcodeAllResponse model constructor.
     * @property {module:model/GetProductByBarcodeAllResponse}
     */
    GetProductByBarcodeAllResponse,

    /**
     * The GetProductByBarcodeKnowledgePanelsResponse model constructor.
     * @property {module:model/GetProductByBarcodeKnowledgePanelsResponse}
     */
    GetProductByBarcodeKnowledgePanelsResponse,

    /**
     * The GetProductByBarcodeResponse model constructor.
     * @property {module:model/GetProductByBarcodeResponse}
     */
    GetProductByBarcodeResponse,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The ImageElement model constructor.
     * @property {module:model/ImageElement}
     */
    ImageElement,

    /**
     * The ImageRole model constructor.
     * @property {module:model/ImageRole}
     */
    ImageRole,

    /**
     * The ImageRoleSizes model constructor.
     * @property {module:model/ImageRoleSizes}
     */
    ImageRoleSizes,

    /**
     * The ImageSize model constructor.
     * @property {module:model/ImageSize}
     */
    ImageSize,

    /**
     * The ImageSizes model constructor.
     * @property {module:model/ImageSizes}
     */
    ImageSizes,

    /**
     * The Ingredient model constructor.
     * @property {module:model/Ingredient}
     */
    Ingredient,

    /**
     * The IngredientPercentMax model constructor.
     * @property {module:model/IngredientPercentMax}
     */
    IngredientPercentMax,

    /**
     * The NumberStringObjectType model constructor.
     * @property {module:model/NumberStringObjectType}
     */
    NumberStringObjectType,

    /**
     * The Nutrient model constructor.
     * @property {module:model/Nutrient}
     */
    Nutrient,

    /**
     * The Nutriscore2021 model constructor.
     * @property {module:model/Nutriscore2021}
     */
    Nutriscore2021,

    /**
     * The Nutriscore20211 model constructor.
     * @property {module:model/Nutriscore20211}
     */
    Nutriscore20211,

    /**
     * The Nutriscore2021Data model constructor.
     * @property {module:model/Nutriscore2021Data}
     */
    Nutriscore2021Data,

    /**
     * The Nutriscore2021Data1 model constructor.
     * @property {module:model/Nutriscore2021Data1}
     */
    Nutriscore2021Data1,

    /**
     * The Nutriscore2023 model constructor.
     * @property {module:model/Nutriscore2023}
     */
    Nutriscore2023,

    /**
     * The Nutriscore20231 model constructor.
     * @property {module:model/Nutriscore20231}
     */
    Nutriscore20231,

    /**
     * The Nutriscore2023Data model constructor.
     * @property {module:model/Nutriscore2023Data}
     */
    Nutriscore2023Data,

    /**
     * The Nutriscore2023DataComponents model constructor.
     * @property {module:model/Nutriscore2023DataComponents}
     */
    Nutriscore2023DataComponents,

    /**
     * The NutriscoreComponent model constructor.
     * @property {module:model/NutriscoreComponent}
     */
    NutriscoreComponent,

    /**
     * The Nutriscores model constructor.
     * @property {module:model/Nutriscores}
     */
    Nutriscores,

    /**
     * The Nutriscores1 model constructor.
     * @property {module:model/Nutriscores1}
     */
    Nutriscores1,

    /**
     * The OcrOnProductResponse model constructor.
     * @property {module:model/OcrOnProductResponse}
     */
    OcrOnProductResponse,

    /**
     * The PackagingComponentREAD model constructor.
     * @property {module:model/PackagingComponentREAD}
     */
    PackagingComponentREAD,

    /**
     * The Panel model constructor.
     * @property {module:model/Panel}
     */
    Panel,

    /**
     * The PanelElement model constructor.
     * @property {module:model/PanelElement}
     */
    PanelElement,

    /**
     * The PanelGroupElement model constructor.
     * @property {module:model/PanelGroupElement}
     */
    PanelGroupElement,

    /**
     * The Panels model constructor.
     * @property {module:model/Panels}
     */
    Panels,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductAllOfManufacturer model constructor.
     * @property {module:model/ProductAllOfManufacturer}
     */
    ProductAllOfManufacturer,

    /**
     * The ProductAttributeGroup model constructor.
     * @property {module:model/ProductAttributeGroup}
     */
    ProductAttributeGroup,

    /**
     * The ProductAttributeGroups model constructor.
     * @property {module:model/ProductAttributeGroups}
     */
    ProductAttributeGroups,

    /**
     * The ProductBase model constructor.
     * @property {module:model/ProductBase}
     */
    ProductBase,

    /**
     * The ProductEcoScore model constructor.
     * @property {module:model/ProductEcoScore}
     */
    ProductEcoScore,

    /**
     * The ProductEcoscoreAdjustments model constructor.
     * @property {module:model/ProductEcoscoreAdjustments}
     */
    ProductEcoscoreAdjustments,

    /**
     * The ProductEcoscoreAdjustmentsOriginsOfIngredients model constructor.
     * @property {module:model/ProductEcoscoreAdjustmentsOriginsOfIngredients}
     */
    ProductEcoscoreAdjustmentsOriginsOfIngredients,

    /**
     * The ProductEcoscoreAdjustmentsPackaging model constructor.
     * @property {module:model/ProductEcoscoreAdjustmentsPackaging}
     */
    ProductEcoscoreAdjustmentsPackaging,

    /**
     * The ProductEcoscoreAdjustmentsProductionSystem model constructor.
     * @property {module:model/ProductEcoscoreAdjustmentsProductionSystem}
     */
    ProductEcoscoreAdjustmentsProductionSystem,

    /**
     * The ProductEcoscoreAdjustmentsThreatenedSpecies model constructor.
     * @property {module:model/ProductEcoscoreAdjustmentsThreatenedSpecies}
     */
    ProductEcoscoreAdjustmentsThreatenedSpecies,

    /**
     * The ProductEcoscoreData model constructor.
     * @property {module:model/ProductEcoscoreData}
     */
    ProductEcoscoreData,

    /**
     * The ProductEcoscoreDataAgribalyse model constructor.
     * @property {module:model/ProductEcoscoreDataAgribalyse}
     */
    ProductEcoscoreDataAgribalyse,

    /**
     * The ProductEcoscoreDataMissing model constructor.
     * @property {module:model/ProductEcoscoreDataMissing}
     */
    ProductEcoscoreDataMissing,

    /**
     * The ProductEcoscoreDataPreviousData model constructor.
     * @property {module:model/ProductEcoscoreDataPreviousData}
     */
    ProductEcoscoreDataPreviousData,

    /**
     * The ProductExtended model constructor.
     * @property {module:model/ProductExtended}
     */
    ProductExtended,

    /**
     * The ProductExtendedCategoriesProperties model constructor.
     * @property {module:model/ProductExtendedCategoriesProperties}
     */
    ProductExtendedCategoriesProperties,

    /**
     * The ProductExtendedOwnerFields model constructor.
     * @property {module:model/ProductExtendedOwnerFields}
     */
    ProductExtendedOwnerFields,

    /**
     * The ProductImages model constructor.
     * @property {module:model/ProductImages}
     */
    ProductImages,

    /**
     * The ProductImagesProperties model constructor.
     * @property {module:model/ProductImagesProperties}
     */
    ProductImagesProperties,

    /**
     * The ProductIngredients model constructor.
     * @property {module:model/ProductIngredients}
     */
    ProductIngredients,

    /**
     * The ProductIngredientsIngredientsAnalysis model constructor.
     * @property {module:model/ProductIngredientsIngredientsAnalysis}
     */
    ProductIngredientsIngredientsAnalysis,

    /**
     * The ProductIngredientsPercentMax model constructor.
     * @property {module:model/ProductIngredientsPercentMax}
     */
    ProductIngredientsPercentMax,

    /**
     * The ProductKnowledgePanels model constructor.
     * @property {module:model/ProductKnowledgePanels}
     */
    ProductKnowledgePanels,

    /**
     * The ProductMetaSource model constructor.
     * @property {module:model/ProductMetaSource}
     */
    ProductMetaSource,

    /**
     * The ProductMetaSourceFields model constructor.
     * @property {module:model/ProductMetaSourceFields}
     */
    ProductMetaSourceFields,

    /**
     * The ProductMetaSourceFieldsOrgGs model constructor.
     * @property {module:model/ProductMetaSourceFieldsOrgGs}
     */
    ProductMetaSourceFieldsOrgGs,

    /**
     * The ProductMetaSourceManufacturer model constructor.
     * @property {module:model/ProductMetaSourceManufacturer}
     */
    ProductMetaSourceManufacturer,

    /**
     * The ProductMetadata model constructor.
     * @property {module:model/ProductMetadata}
     */
    ProductMetadata,

    /**
     * The ProductMisc model constructor.
     * @property {module:model/ProductMisc}
     */
    ProductMisc,

    /**
     * The ProductMiscNutrientLevels model constructor.
     * @property {module:model/ProductMiscNutrientLevels}
     */
    ProductMiscNutrientLevels,

    /**
     * The ProductNutriscore model constructor.
     * @property {module:model/ProductNutriscore}
     */
    ProductNutriscore,

    /**
     * The ProductNutrition model constructor.
     * @property {module:model/ProductNutrition}
     */
    ProductNutrition,

    /**
     * The ProductNutritionNutriments model constructor.
     * @property {module:model/ProductNutritionNutriments}
     */
    ProductNutritionNutriments,

    /**
     * The ProductNutritionNutriscoreData model constructor.
     * @property {module:model/ProductNutritionNutriscoreData}
     */
    ProductNutritionNutriscoreData,

    /**
     * The ProductQuality model constructor.
     * @property {module:model/ProductQuality}
     */
    ProductQuality,

    /**
     * The ProductSelectedImages model constructor.
     * @property {module:model/ProductSelectedImages}
     */
    ProductSelectedImages,

    /**
     * The ProductSelectedImagesIngredients model constructor.
     * @property {module:model/ProductSelectedImagesIngredients}
     */
    ProductSelectedImagesIngredients,

    /**
     * The ProductTags model constructor.
     * @property {module:model/ProductTags}
     */
    ProductTags,

    /**
     * The RotateAPhotoResponse model constructor.
     * @property {module:model/RotateAPhotoResponse}
     */
    RotateAPhotoResponse,

    /**
     * The RotateAPhotoResponseImage model constructor.
     * @property {module:model/RotateAPhotoResponseImage}
     */
    RotateAPhotoResponseImage,

    /**
     * The SearchForProductsResponse model constructor.
     * @property {module:model/SearchForProductsResponse}
     */
    SearchForProductsResponse,

    /**
     * The TableColumn model constructor.
     * @property {module:model/TableColumn}
     */
    TableColumn,

    /**
     * The TableElement model constructor.
     * @property {module:model/TableElement}
     */
    TableElement,

    /**
     * The TextElement model constructor.
     * @property {module:model/TextElement}
     */
    TextElement,

    /**
     * The TitleElement model constructor.
     * @property {module:model/TitleElement}
     */
    TitleElement,

    /**
     * The UnselectAPhotoResponse model constructor.
     * @property {module:model/UnselectAPhotoResponse}
     */
    UnselectAPhotoResponse,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The AuxiliaryOperationsApi service constructor.
    * @property {module:api/AuxiliaryOperationsApi}
    */
    AuxiliaryOperationsApi,

    /**
    * The PersonalSearchApi service constructor.
    * @property {module:api/PersonalSearchApi}
    */
    PersonalSearchApi,

    /**
    * The ReadRequestsApi service constructor.
    * @property {module:api/ReadRequestsApi}
    */
    ReadRequestsApi,

    /**
    * The WriteRequestsApi service constructor.
    * @property {module:api/WriteRequestsApi}
    */
    WriteRequestsApi
};
